/**
 * Bunli plugin: filter `ndea view` positional completions to zarr stores
 * and YAML configs.
 *
 * Mechanism: Cobra/Tab dynamic completion protocol:
 *   1. The shell completion script (generated by @bunli/plugin-completions)
 *      invokes `ndea complete -- <argv...>` on every TAB press.
 *   2. The binary writes one candidate per line on stdout, then a final
 *      `:<int>` line whose value is a bitfield of ShellCompDirective flags.
 *   3. The shell honours the directive: for `FilterFileExt` (bit 3 = 8)
 *      it consumes the candidate lines as an extension list and runs its
 *      own glob.
 *
 * For `ndea view <TAB>` we want the shell to glob `*.zarr | *.yaml | *.yml`.
 * On every supported shell those globs match path components by name :
 * so a directory named `myset.zarr/` is included alongside flat files.
 * That covers AnnData / MuData / OME-Zarr stores (all ".zarr" by
 * convention) plus YAML project configs in one filter.
 *
 * We hook this in via `beforeCommand`: when bunli is about to dispatch
 * the upstream `complete` handler from @bunli/plugin-completions, we
 * inspect the args, short-circuit + emit the directive ourselves when
 * the user is completing a `view` positional, and otherwise fall
 * through to the upstream handler unchanged.
 *
 * This is the small, surgical version of "extend completion behaviour
 * for one command's positional". The principled version is a richer
 * extension API on @bunli/plugin-completions itself; we'll upstream
 * that pattern when this footprint grows.
 */

import { createPlugin } from "@bunli/core/plugin";

/** ShellCompDirective.ShellCompDirectiveFilterFileExt: Cobra protocol bit 3. */
const FILTER_FILE_EXT = 1 << 3;

/** Extensions matched against path components by every supported shell. */
const VIEW_POSITIONAL_EXTENSIONS = ["zarr", "yaml", "yml"] as const;

const SHELL_NAMES = new Set(["bash", "zsh", "fish"]);

export const viewCompletionPlugin = createPlugin({
  name: "ndea-view-completion",
  beforeCommand(ctx) {
    // @bunli/plugin-completions registers a single `completions` command
    // that handles both the script generator (`ndea completions zsh`) and
    // the dynamic protocol callback (`ndea complete -- <argv>`: bunli's
    // parser does prefix-match resolution, so `complete` routes to
    // `completions`).
    if (ctx.command !== "completions") return;

    // Walk raw process.argv instead of ctx.args because bunli's parser
    // strips anything that looks flag-like (e.g. an in-progress `--po`)
    // before we see the parsed args. The Cobra protocol passes the
    // command line being completed AFTER a `--` separator, so the only
    // reliable source of "what the user actually typed" is the raw argv.
    const dashDashIdx = process.argv.indexOf("--");
    if (dashDashIdx === -1) return; // script-gen path (no protocol --)
    const rawArgs = process.argv.slice(dashDashIdx + 1);
    if (rawArgs.length === 0) return;

    // First raw arg is the command being completed.
    if (SHELL_NAMES.has(rawArgs[0])) return; // belt-and-suspenders
    if (rawArgs[0] !== "view") return;

    // Skip when the user is completing a flag (`ndea view --po<TAB>`) :
    // any token starting with `-` after `view` means we're in a flag
    // context, let upstream emit flag/value suggestions.
    const last = rawArgs[rawArgs.length - 1] ?? "";
    if (last.startsWith("-")) return;

    // Emit the FilterFileExt directive and exit before bunli dispatches
    // the upstream `complete` handler. Each candidate is one line; the
    // trailing `:N` line is the directive bitfield.
    for (const ext of VIEW_POSITIONAL_EXTENSIONS) {
      process.stdout.write(`${ext}\n`);
    }
    process.stdout.write(`:${FILTER_FILE_EXT}\n`);
    process.exit(0);
  },
});
