// Generated by scripts/import-cmap-napari.mjs. Do not edit by hand.
// Source: cmap napari (https://github.com/pyapp-kit/cmap/tree/main/src/cmap/data/napari)
// Run `pnpm import:napari` to regenerate.

/** HiLo: miscellaneous */
export const HILO_LUT = Float32Array.of(0.0, 0.0, 0.0, 1.0, 1.0, 1.0);

/** nan: miscellaneous */
export const NAN_LUT = Float32Array.of(0.0, 0.0, 0.0, 1.0, 1.0, 1.0);
