// AUTO-GENERATED by scripts/build.ts — do not edit.
// Maps frontend asset relative paths to their resolved file paths.
// In dev mode paths point at frontend/dist/; in compiled binaries they
// resolve to $bunfs/ entries embedded via `with { type: "file" }`.

import _0 from "../../frontend/dist/index.html" with { type: "file" };
import _1 from "../../frontend/dist/assets/geist-mono-cyrillic-wght-normal-BZdD_g9V.woff2" with { type: "file" };
import _2 from "../../frontend/dist/assets/geist-mono-latin-ext-wght-normal-b6lpi8_2.woff2" with { type: "file" };
import _3 from "../../frontend/dist/assets/index-BnGr910p.js" with { type: "file" };
import _4 from "../../frontend/dist/assets/input-group-D-pM6F6-.js" with { type: "file" };
import _5 from "../../frontend/dist/assets/chunk-INHXZS53-DiyuLb3Z-wPY1n4bv.js" with { type: "file" };
import _6 from "../../frontend/dist/assets/geist-mono-latin-wght-normal-Cjtb1TV-.woff2" with { type: "file" };
import _7 from "../../frontend/dist/assets/modern-BCqGWBa1.js" with { type: "file" };
import _8 from "../../frontend/dist/assets/blosc-BOWv2fO7-C3jKadcc.js" with { type: "file" };
import _9 from "../../frontend/dist/assets/ExportDialog-BxNLnzpq.js" with { type: "file" };
import _10 from "../../frontend/dist/assets/lz4-DUlZKApi-CWl8vXG0.js" with { type: "file" };
import _11 from "../../frontend/dist/assets/zstd-DnzmycJs-Jduwv741.js" with { type: "file" };
import _12 from "../../frontend/dist/assets/chunk-DECur_0Z.js" with { type: "file" };
import _13 from "../../frontend/dist/assets/index-DcGaDGiZ.css" with { type: "file" };

export const EMBEDDED_ASSETS: Record<string, string> = {
    "index.html": _0,
    "assets/geist-mono-cyrillic-wght-normal-BZdD_g9V.woff2": _1,
    "assets/geist-mono-latin-ext-wght-normal-b6lpi8_2.woff2": _2,
    "assets/index-BnGr910p.js": _3,
    "assets/input-group-D-pM6F6-.js": _4,
    "assets/chunk-INHXZS53-DiyuLb3Z-wPY1n4bv.js": _5,
    "assets/geist-mono-latin-wght-normal-Cjtb1TV-.woff2": _6,
    "assets/modern-BCqGWBa1.js": _7,
    "assets/blosc-BOWv2fO7-C3jKadcc.js": _8,
    "assets/ExportDialog-BxNLnzpq.js": _9,
    "assets/lz4-DUlZKApi-CWl8vXG0.js": _10,
    "assets/zstd-DnzmycJs-Jduwv741.js": _11,
    "assets/chunk-DECur_0Z.js": _12,
    "assets/index-DcGaDGiZ.css": _13,
};
