// Generated by scripts/import-cmap-bids.mjs. Do not edit by hand.

import { linearFromLut } from "../build";
import * as data from "../data/bids.generated";

export const fake_parula = linearFromLut({ name: "fake_parula", lut: data.FAKE_PARULA_LUT });
export const inferno = linearFromLut({ name: "inferno", lut: data.INFERNO_LUT });
export const magma = linearFromLut({ name: "magma", lut: data.MAGMA_LUT });
export const plasma = linearFromLut({ name: "plasma", lut: data.PLASMA_LUT });
export const viridis = linearFromLut({ name: "viridis", lut: data.VIRIDIS_LUT });
