// Generated by scripts/import-cmap-chrisluts.mjs. Do not edit by hand.

import { linearFromLut } from "../build";
import * as data from "../data/chrisluts.generated";

export const BMR_3C = linearFromLut({ name: "BMR_3C", lut: data.BMR_3C_LUT });
export const BOP_Blue = linearFromLut({ name: "BOP_Blue", lut: data.BOP_BLUE_LUT });
export const BOP_Orange = linearFromLut({ name: "BOP_Orange", lut: data.BOP_ORANGE_LUT });
export const BOP_Purple = linearFromLut({ name: "BOP_Purple", lut: data.BOP_PURPLE_LUT });
export const CGY_3C = linearFromLut({ name: "CGY_3C", lut: data.CGY_3C_LUT });
export const I_Blue = linearFromLut({ name: "I_Blue", lut: data.I_BLUE_LUT });
export const I_Bordeaux = linearFromLut({ name: "I_Bordeaux", lut: data.I_BORDEAUX_LUT });
export const I_Cyan = linearFromLut({ name: "I_Cyan", lut: data.I_CYAN_LUT });
export const I_Forest = linearFromLut({ name: "I_Forest", lut: data.I_FOREST_LUT });
export const I_Green = linearFromLut({ name: "I_Green", lut: data.I_GREEN_LUT });
export const I_Magenta = linearFromLut({ name: "I_Magenta", lut: data.I_MAGENTA_LUT });
export const I_Orange = linearFromLut({ name: "I_Orange", lut: data.I_ORANGE_LUT });
export const I_Purple = linearFromLut({ name: "I_Purple", lut: data.I_PURPLE_LUT });
export const I_Red = linearFromLut({ name: "I_Red", lut: data.I_RED_LUT });
export const I_Yellow = linearFromLut({ name: "I_Yellow", lut: data.I_YELLOW_LUT });
export const OPF_Fresh = linearFromLut({ name: "OPF_Fresh", lut: data.OPF_FRESH_LUT });
export const OPF_Orange = linearFromLut({ name: "OPF_Orange", lut: data.OPF_ORANGE_LUT });
export const OPF_Purple = linearFromLut({ name: "OPF_Purple", lut: data.OPF_PURPLE_LUT });
export const RMB_3C = linearFromLut({ name: "RMB_3C", lut: data.RMB_3C_LUT });
export const YGC_3C = linearFromLut({ name: "YGC_3C", lut: data.YGC_3C_LUT });
