// Generated by scripts/import-cmap-cividis.mjs. Do not edit by hand.

import { linearFromLut } from "../build";
import * as data from "../data/cividis.generated";

export const cividis = linearFromLut({ name: "cividis", lut: data.CIVIDIS_LUT });
