// Generated by scripts/import-cmap-cmocean.mjs. Do not edit by hand.

import { linearFromLut } from "../build";
import * as data from "../data/cmocean.generated";

export const algae = linearFromLut({ name: "algae", lut: data.ALGAE_LUT });
export const amp = linearFromLut({ name: "amp", lut: data.AMP_LUT });
export const balance = linearFromLut({ name: "balance", lut: data.BALANCE_LUT });
export const balance_blue = linearFromLut({ name: "balance_blue", lut: data.BALANCE_BLUE_LUT });
export const curl = linearFromLut({ name: "curl", lut: data.CURL_LUT });
export const curl_pink = linearFromLut({ name: "curl_pink", lut: data.CURL_PINK_LUT });
export const deep = linearFromLut({ name: "deep", lut: data.DEEP_LUT });
export const delta = linearFromLut({ name: "delta", lut: data.DELTA_LUT });
export const delta_blue = linearFromLut({ name: "delta_blue", lut: data.DELTA_BLUE_LUT });
export const dense = linearFromLut({ name: "dense", lut: data.DENSE_LUT });
export const diff = linearFromLut({ name: "diff", lut: data.DIFF_LUT });
export const haline = linearFromLut({ name: "haline", lut: data.HALINE_LUT });
export const ice = linearFromLut({ name: "ice", lut: data.ICE_LUT });
export const matter = linearFromLut({ name: "matter", lut: data.MATTER_LUT });
export const oxy = linearFromLut({ name: "oxy", lut: data.OXY_LUT });
export const phase = linearFromLut({ name: "phase", lut: data.PHASE_LUT });
export const rain = linearFromLut({ name: "rain", lut: data.RAIN_LUT });
export const solar = linearFromLut({ name: "solar", lut: data.SOLAR_LUT });
export const speed = linearFromLut({ name: "speed", lut: data.SPEED_LUT });
export const tarn = linearFromLut({ name: "tarn", lut: data.TARN_LUT });
export const tempo = linearFromLut({ name: "tempo", lut: data.TEMPO_LUT });
export const thermal = linearFromLut({ name: "thermal", lut: data.THERMAL_LUT });
export const topo = linearFromLut({ name: "topo", lut: data.TOPO_LUT });
export const turbid = linearFromLut({ name: "turbid", lut: data.TURBID_LUT });
