// Generated by scripts/import-cmap-colorbrewer.mjs. Do not edit by hand.

import { linearFromLut, discreteFromRgbLut } from "../build";
import * as data from "../data/colorbrewer.generated";

/** Accent (qualitative, discrete) */
export const Accent = discreteFromRgbLut("Accent", data.ACCENT_8_LUT);
/** Accent_3 (qualitative, discrete) */
export const Accent_3 = discreteFromRgbLut("Accent_3", data.ACCENT_3_LUT);
/** Accent_4 (qualitative, discrete) */
export const Accent_4 = discreteFromRgbLut("Accent_4", data.ACCENT_4_LUT);
/** Accent_5 (qualitative, discrete) */
export const Accent_5 = discreteFromRgbLut("Accent_5", data.ACCENT_5_LUT);
/** Accent_6 (qualitative, discrete) */
export const Accent_6 = discreteFromRgbLut("Accent_6", data.ACCENT_6_LUT);
/** Accent_7 (qualitative, discrete) */
export const Accent_7 = discreteFromRgbLut("Accent_7", data.ACCENT_7_LUT);
/** Accent_8 (qualitative, discrete) */
export const Accent_8 = discreteFromRgbLut("Accent_8", data.ACCENT_8_LUT);
/** Blues (sequential) */
export const Blues = linearFromLut({ name: "Blues", lut: data.BLUES_9_LUT });
/** Blues_3 (sequential, discrete) */
export const Blues_3 = discreteFromRgbLut("Blues_3", data.BLUES_3_LUT);
/** Blues_4 (sequential, discrete) */
export const Blues_4 = discreteFromRgbLut("Blues_4", data.BLUES_4_LUT);
/** Blues_5 (sequential, discrete) */
export const Blues_5 = discreteFromRgbLut("Blues_5", data.BLUES_5_LUT);
/** Blues_6 (sequential, discrete) */
export const Blues_6 = discreteFromRgbLut("Blues_6", data.BLUES_6_LUT);
/** Blues_7 (sequential, discrete) */
export const Blues_7 = discreteFromRgbLut("Blues_7", data.BLUES_7_LUT);
/** Blues_8 (sequential, discrete) */
export const Blues_8 = discreteFromRgbLut("Blues_8", data.BLUES_8_LUT);
/** Blues_9 (sequential, discrete) */
export const Blues_9 = discreteFromRgbLut("Blues_9", data.BLUES_9_LUT);
/** BrBG (diverging) */
export const BrBG = linearFromLut({ name: "BrBG", lut: data.BRBG_11_LUT });
/** BrBG_10 (diverging, discrete) */
export const BrBG_10 = discreteFromRgbLut("BrBG_10", data.BRBG_10_LUT);
/** BrBG_11 (diverging, discrete) */
export const BrBG_11 = discreteFromRgbLut("BrBG_11", data.BRBG_11_LUT);
/** BrBG_3 (diverging, discrete) */
export const BrBG_3 = discreteFromRgbLut("BrBG_3", data.BRBG_3_LUT);
/** BrBG_4 (diverging, discrete) */
export const BrBG_4 = discreteFromRgbLut("BrBG_4", data.BRBG_4_LUT);
/** BrBG_5 (diverging, discrete) */
export const BrBG_5 = discreteFromRgbLut("BrBG_5", data.BRBG_5_LUT);
/** BrBG_6 (diverging, discrete) */
export const BrBG_6 = discreteFromRgbLut("BrBG_6", data.BRBG_6_LUT);
/** BrBG_7 (diverging, discrete) */
export const BrBG_7 = discreteFromRgbLut("BrBG_7", data.BRBG_7_LUT);
/** BrBG_8 (diverging, discrete) */
export const BrBG_8 = discreteFromRgbLut("BrBG_8", data.BRBG_8_LUT);
/** BrBG_9 (diverging, discrete) */
export const BrBG_9 = discreteFromRgbLut("BrBG_9", data.BRBG_9_LUT);
/** BuGn (sequential) */
export const BuGn = linearFromLut({ name: "BuGn", lut: data.BUGN_9_LUT });
/** BuGn_3 (sequential, discrete) */
export const BuGn_3 = discreteFromRgbLut("BuGn_3", data.BUGN_3_LUT);
/** BuGn_4 (sequential, discrete) */
export const BuGn_4 = discreteFromRgbLut("BuGn_4", data.BUGN_4_LUT);
/** BuGn_5 (sequential, discrete) */
export const BuGn_5 = discreteFromRgbLut("BuGn_5", data.BUGN_5_LUT);
/** BuGn_6 (sequential, discrete) */
export const BuGn_6 = discreteFromRgbLut("BuGn_6", data.BUGN_6_LUT);
/** BuGn_7 (sequential, discrete) */
export const BuGn_7 = discreteFromRgbLut("BuGn_7", data.BUGN_7_LUT);
/** BuGn_8 (sequential, discrete) */
export const BuGn_8 = discreteFromRgbLut("BuGn_8", data.BUGN_8_LUT);
/** BuGn_9 (sequential, discrete) */
export const BuGn_9 = discreteFromRgbLut("BuGn_9", data.BUGN_9_LUT);
/** BuPu (sequential) */
export const BuPu = linearFromLut({ name: "BuPu", lut: data.BUPU_9_LUT });
/** BuPu_3 (sequential, discrete) */
export const BuPu_3 = discreteFromRgbLut("BuPu_3", data.BUPU_3_LUT);
/** BuPu_4 (sequential, discrete) */
export const BuPu_4 = discreteFromRgbLut("BuPu_4", data.BUPU_4_LUT);
/** BuPu_5 (sequential, discrete) */
export const BuPu_5 = discreteFromRgbLut("BuPu_5", data.BUPU_5_LUT);
/** BuPu_6 (sequential, discrete) */
export const BuPu_6 = discreteFromRgbLut("BuPu_6", data.BUPU_6_LUT);
/** BuPu_7 (sequential, discrete) */
export const BuPu_7 = discreteFromRgbLut("BuPu_7", data.BUPU_7_LUT);
/** BuPu_8 (sequential, discrete) */
export const BuPu_8 = discreteFromRgbLut("BuPu_8", data.BUPU_8_LUT);
/** BuPu_9 (sequential, discrete) */
export const BuPu_9 = discreteFromRgbLut("BuPu_9", data.BUPU_9_LUT);
/** Dark2 (qualitative, discrete) */
export const Dark2 = discreteFromRgbLut("Dark2", data.DARK2_8_LUT);
/** Dark2_3 (qualitative, discrete) */
export const Dark2_3 = discreteFromRgbLut("Dark2_3", data.DARK2_3_LUT);
/** Dark2_4 (qualitative, discrete) */
export const Dark2_4 = discreteFromRgbLut("Dark2_4", data.DARK2_4_LUT);
/** Dark2_5 (qualitative, discrete) */
export const Dark2_5 = discreteFromRgbLut("Dark2_5", data.DARK2_5_LUT);
/** Dark2_6 (qualitative, discrete) */
export const Dark2_6 = discreteFromRgbLut("Dark2_6", data.DARK2_6_LUT);
/** Dark2_7 (qualitative, discrete) */
export const Dark2_7 = discreteFromRgbLut("Dark2_7", data.DARK2_7_LUT);
/** Dark2_8 (qualitative, discrete) */
export const Dark2_8 = discreteFromRgbLut("Dark2_8", data.DARK2_8_LUT);
/** GnBu (sequential) */
export const GnBu = linearFromLut({ name: "GnBu", lut: data.GNBU_9_LUT });
/** GnBu_3 (sequential, discrete) */
export const GnBu_3 = discreteFromRgbLut("GnBu_3", data.GNBU_3_LUT);
/** GnBu_4 (sequential, discrete) */
export const GnBu_4 = discreteFromRgbLut("GnBu_4", data.GNBU_4_LUT);
/** GnBu_5 (sequential, discrete) */
export const GnBu_5 = discreteFromRgbLut("GnBu_5", data.GNBU_5_LUT);
/** GnBu_6 (sequential, discrete) */
export const GnBu_6 = discreteFromRgbLut("GnBu_6", data.GNBU_6_LUT);
/** GnBu_7 (sequential, discrete) */
export const GnBu_7 = discreteFromRgbLut("GnBu_7", data.GNBU_7_LUT);
/** GnBu_8 (sequential, discrete) */
export const GnBu_8 = discreteFromRgbLut("GnBu_8", data.GNBU_8_LUT);
/** GnBu_9 (sequential, discrete) */
export const GnBu_9 = discreteFromRgbLut("GnBu_9", data.GNBU_9_LUT);
/** Greens (sequential) */
export const Greens = linearFromLut({ name: "Greens", lut: data.GREENS_9_LUT });
/** Greens_3 (sequential, discrete) */
export const Greens_3 = discreteFromRgbLut("Greens_3", data.GREENS_3_LUT);
/** Greens_4 (sequential, discrete) */
export const Greens_4 = discreteFromRgbLut("Greens_4", data.GREENS_4_LUT);
/** Greens_5 (sequential, discrete) */
export const Greens_5 = discreteFromRgbLut("Greens_5", data.GREENS_5_LUT);
/** Greens_6 (sequential, discrete) */
export const Greens_6 = discreteFromRgbLut("Greens_6", data.GREENS_6_LUT);
/** Greens_7 (sequential, discrete) */
export const Greens_7 = discreteFromRgbLut("Greens_7", data.GREENS_7_LUT);
/** Greens_8 (sequential, discrete) */
export const Greens_8 = discreteFromRgbLut("Greens_8", data.GREENS_8_LUT);
/** Greens_9 (sequential, discrete) */
export const Greens_9 = discreteFromRgbLut("Greens_9", data.GREENS_9_LUT);
/** Greys (sequential) */
export const Greys = linearFromLut({ name: "Greys", lut: data.GREYS_9_LUT });
/** Greys_3 (sequential, discrete) */
export const Greys_3 = discreteFromRgbLut("Greys_3", data.GREYS_3_LUT);
/** Greys_4 (sequential, discrete) */
export const Greys_4 = discreteFromRgbLut("Greys_4", data.GREYS_4_LUT);
/** Greys_5 (sequential, discrete) */
export const Greys_5 = discreteFromRgbLut("Greys_5", data.GREYS_5_LUT);
/** Greys_6 (sequential, discrete) */
export const Greys_6 = discreteFromRgbLut("Greys_6", data.GREYS_6_LUT);
/** Greys_7 (sequential, discrete) */
export const Greys_7 = discreteFromRgbLut("Greys_7", data.GREYS_7_LUT);
/** Greys_8 (sequential, discrete) */
export const Greys_8 = discreteFromRgbLut("Greys_8", data.GREYS_8_LUT);
/** Greys_9 (sequential, discrete) */
export const Greys_9 = discreteFromRgbLut("Greys_9", data.GREYS_9_LUT);
/** OrRd (sequential) */
export const OrRd = linearFromLut({ name: "OrRd", lut: data.ORRD_9_LUT });
/** OrRd_3 (sequential, discrete) */
export const OrRd_3 = discreteFromRgbLut("OrRd_3", data.ORRD_3_LUT);
/** OrRd_4 (sequential, discrete) */
export const OrRd_4 = discreteFromRgbLut("OrRd_4", data.ORRD_4_LUT);
/** OrRd_5 (sequential, discrete) */
export const OrRd_5 = discreteFromRgbLut("OrRd_5", data.ORRD_5_LUT);
/** OrRd_6 (sequential, discrete) */
export const OrRd_6 = discreteFromRgbLut("OrRd_6", data.ORRD_6_LUT);
/** OrRd_7 (sequential, discrete) */
export const OrRd_7 = discreteFromRgbLut("OrRd_7", data.ORRD_7_LUT);
/** OrRd_8 (sequential, discrete) */
export const OrRd_8 = discreteFromRgbLut("OrRd_8", data.ORRD_8_LUT);
/** OrRd_9 (sequential, discrete) */
export const OrRd_9 = discreteFromRgbLut("OrRd_9", data.ORRD_9_LUT);
/** Oranges (sequential) */
export const Oranges = linearFromLut({ name: "Oranges", lut: data.ORANGES_9_LUT });
/** Oranges_3 (sequential, discrete) */
export const Oranges_3 = discreteFromRgbLut("Oranges_3", data.ORANGES_3_LUT);
/** Oranges_4 (sequential, discrete) */
export const Oranges_4 = discreteFromRgbLut("Oranges_4", data.ORANGES_4_LUT);
/** Oranges_5 (sequential, discrete) */
export const Oranges_5 = discreteFromRgbLut("Oranges_5", data.ORANGES_5_LUT);
/** Oranges_6 (sequential, discrete) */
export const Oranges_6 = discreteFromRgbLut("Oranges_6", data.ORANGES_6_LUT);
/** Oranges_7 (sequential, discrete) */
export const Oranges_7 = discreteFromRgbLut("Oranges_7", data.ORANGES_7_LUT);
/** Oranges_8 (sequential, discrete) */
export const Oranges_8 = discreteFromRgbLut("Oranges_8", data.ORANGES_8_LUT);
/** Oranges_9 (sequential, discrete) */
export const Oranges_9 = discreteFromRgbLut("Oranges_9", data.ORANGES_9_LUT);
/** PRGn (diverging) */
export const PRGn = linearFromLut({ name: "PRGn", lut: data.PRGN_11_LUT });
/** PRGn_10 (diverging, discrete) */
export const PRGn_10 = discreteFromRgbLut("PRGn_10", data.PRGN_10_LUT);
/** PRGn_11 (diverging, discrete) */
export const PRGn_11 = discreteFromRgbLut("PRGn_11", data.PRGN_11_LUT);
/** PRGn_3 (diverging, discrete) */
export const PRGn_3 = discreteFromRgbLut("PRGn_3", data.PRGN_3_LUT);
/** PRGn_4 (diverging, discrete) */
export const PRGn_4 = discreteFromRgbLut("PRGn_4", data.PRGN_4_LUT);
/** PRGn_5 (diverging, discrete) */
export const PRGn_5 = discreteFromRgbLut("PRGn_5", data.PRGN_5_LUT);
/** PRGn_6 (diverging, discrete) */
export const PRGn_6 = discreteFromRgbLut("PRGn_6", data.PRGN_6_LUT);
/** PRGn_7 (diverging, discrete) */
export const PRGn_7 = discreteFromRgbLut("PRGn_7", data.PRGN_7_LUT);
/** PRGn_8 (diverging, discrete) */
export const PRGn_8 = discreteFromRgbLut("PRGn_8", data.PRGN_8_LUT);
/** PRGn_9 (diverging, discrete) */
export const PRGn_9 = discreteFromRgbLut("PRGn_9", data.PRGN_9_LUT);
/** Paired (qualitative, discrete) */
export const Paired = discreteFromRgbLut("Paired", data.PAIRED_12_LUT);
/** Paired_10 (qualitative, discrete) */
export const Paired_10 = discreteFromRgbLut("Paired_10", data.PAIRED_10_LUT);
/** Paired_11 (qualitative, discrete) */
export const Paired_11 = discreteFromRgbLut("Paired_11", data.PAIRED_11_LUT);
/** Paired_12 (qualitative, discrete) */
export const Paired_12 = discreteFromRgbLut("Paired_12", data.PAIRED_12_LUT);
/** Paired_3 (qualitative, discrete) */
export const Paired_3 = discreteFromRgbLut("Paired_3", data.PAIRED_3_LUT);
/** Paired_4 (qualitative, discrete) */
export const Paired_4 = discreteFromRgbLut("Paired_4", data.PAIRED_4_LUT);
/** Paired_5 (qualitative, discrete) */
export const Paired_5 = discreteFromRgbLut("Paired_5", data.PAIRED_5_LUT);
/** Paired_6 (qualitative, discrete) */
export const Paired_6 = discreteFromRgbLut("Paired_6", data.PAIRED_6_LUT);
/** Paired_7 (qualitative, discrete) */
export const Paired_7 = discreteFromRgbLut("Paired_7", data.PAIRED_7_LUT);
/** Paired_8 (qualitative, discrete) */
export const Paired_8 = discreteFromRgbLut("Paired_8", data.PAIRED_8_LUT);
/** Paired_9 (qualitative, discrete) */
export const Paired_9 = discreteFromRgbLut("Paired_9", data.PAIRED_9_LUT);
/** Pastel1 (qualitative, discrete) */
export const Pastel1 = discreteFromRgbLut("Pastel1", data.PASTEL1_9_LUT);
/** Pastel1_3 (qualitative, discrete) */
export const Pastel1_3 = discreteFromRgbLut("Pastel1_3", data.PASTEL1_3_LUT);
/** Pastel1_4 (qualitative, discrete) */
export const Pastel1_4 = discreteFromRgbLut("Pastel1_4", data.PASTEL1_4_LUT);
/** Pastel1_5 (qualitative, discrete) */
export const Pastel1_5 = discreteFromRgbLut("Pastel1_5", data.PASTEL1_5_LUT);
/** Pastel1_6 (qualitative, discrete) */
export const Pastel1_6 = discreteFromRgbLut("Pastel1_6", data.PASTEL1_6_LUT);
/** Pastel1_7 (qualitative, discrete) */
export const Pastel1_7 = discreteFromRgbLut("Pastel1_7", data.PASTEL1_7_LUT);
/** Pastel1_8 (qualitative, discrete) */
export const Pastel1_8 = discreteFromRgbLut("Pastel1_8", data.PASTEL1_8_LUT);
/** Pastel1_9 (qualitative, discrete) */
export const Pastel1_9 = discreteFromRgbLut("Pastel1_9", data.PASTEL1_9_LUT);
/** Pastel2 (qualitative, discrete) */
export const Pastel2 = discreteFromRgbLut("Pastel2", data.PASTEL2_8_LUT);
/** Pastel2_3 (qualitative, discrete) */
export const Pastel2_3 = discreteFromRgbLut("Pastel2_3", data.PASTEL2_3_LUT);
/** Pastel2_4 (qualitative, discrete) */
export const Pastel2_4 = discreteFromRgbLut("Pastel2_4", data.PASTEL2_4_LUT);
/** Pastel2_5 (qualitative, discrete) */
export const Pastel2_5 = discreteFromRgbLut("Pastel2_5", data.PASTEL2_5_LUT);
/** Pastel2_6 (qualitative, discrete) */
export const Pastel2_6 = discreteFromRgbLut("Pastel2_6", data.PASTEL2_6_LUT);
/** Pastel2_7 (qualitative, discrete) */
export const Pastel2_7 = discreteFromRgbLut("Pastel2_7", data.PASTEL2_7_LUT);
/** Pastel2_8 (qualitative, discrete) */
export const Pastel2_8 = discreteFromRgbLut("Pastel2_8", data.PASTEL2_8_LUT);
/** PiYG (diverging) */
export const PiYG = linearFromLut({ name: "PiYG", lut: data.PIYG_11_LUT });
/** PiYG_10 (diverging, discrete) */
export const PiYG_10 = discreteFromRgbLut("PiYG_10", data.PIYG_10_LUT);
/** PiYG_11 (diverging, discrete) */
export const PiYG_11 = discreteFromRgbLut("PiYG_11", data.PIYG_11_LUT);
/** PiYG_3 (diverging, discrete) */
export const PiYG_3 = discreteFromRgbLut("PiYG_3", data.PIYG_3_LUT);
/** PiYG_4 (diverging, discrete) */
export const PiYG_4 = discreteFromRgbLut("PiYG_4", data.PIYG_4_LUT);
/** PiYG_5 (diverging, discrete) */
export const PiYG_5 = discreteFromRgbLut("PiYG_5", data.PIYG_5_LUT);
/** PiYG_6 (diverging, discrete) */
export const PiYG_6 = discreteFromRgbLut("PiYG_6", data.PIYG_6_LUT);
/** PiYG_7 (diverging, discrete) */
export const PiYG_7 = discreteFromRgbLut("PiYG_7", data.PIYG_7_LUT);
/** PiYG_8 (diverging, discrete) */
export const PiYG_8 = discreteFromRgbLut("PiYG_8", data.PIYG_8_LUT);
/** PiYG_9 (diverging, discrete) */
export const PiYG_9 = discreteFromRgbLut("PiYG_9", data.PIYG_9_LUT);
/** PuBu (sequential) */
export const PuBu = linearFromLut({ name: "PuBu", lut: data.PUBU_9_LUT });
/** PuBuGn (sequential) */
export const PuBuGn = linearFromLut({ name: "PuBuGn", lut: data.PUBUGN_9_LUT });
/** PuBuGn_3 (sequential, discrete) */
export const PuBuGn_3 = discreteFromRgbLut("PuBuGn_3", data.PUBUGN_3_LUT);
/** PuBuGn_4 (sequential, discrete) */
export const PuBuGn_4 = discreteFromRgbLut("PuBuGn_4", data.PUBUGN_4_LUT);
/** PuBuGn_5 (sequential, discrete) */
export const PuBuGn_5 = discreteFromRgbLut("PuBuGn_5", data.PUBUGN_5_LUT);
/** PuBuGn_6 (sequential, discrete) */
export const PuBuGn_6 = discreteFromRgbLut("PuBuGn_6", data.PUBUGN_6_LUT);
/** PuBuGn_7 (sequential, discrete) */
export const PuBuGn_7 = discreteFromRgbLut("PuBuGn_7", data.PUBUGN_7_LUT);
/** PuBuGn_8 (sequential, discrete) */
export const PuBuGn_8 = discreteFromRgbLut("PuBuGn_8", data.PUBUGN_8_LUT);
/** PuBuGn_9 (sequential, discrete) */
export const PuBuGn_9 = discreteFromRgbLut("PuBuGn_9", data.PUBUGN_9_LUT);
/** PuBu_3 (sequential, discrete) */
export const PuBu_3 = discreteFromRgbLut("PuBu_3", data.PUBU_3_LUT);
/** PuBu_4 (sequential, discrete) */
export const PuBu_4 = discreteFromRgbLut("PuBu_4", data.PUBU_4_LUT);
/** PuBu_5 (sequential, discrete) */
export const PuBu_5 = discreteFromRgbLut("PuBu_5", data.PUBU_5_LUT);
/** PuBu_6 (sequential, discrete) */
export const PuBu_6 = discreteFromRgbLut("PuBu_6", data.PUBU_6_LUT);
/** PuBu_7 (sequential, discrete) */
export const PuBu_7 = discreteFromRgbLut("PuBu_7", data.PUBU_7_LUT);
/** PuBu_8 (sequential, discrete) */
export const PuBu_8 = discreteFromRgbLut("PuBu_8", data.PUBU_8_LUT);
/** PuBu_9 (sequential, discrete) */
export const PuBu_9 = discreteFromRgbLut("PuBu_9", data.PUBU_9_LUT);
/** PuOr (diverging) */
export const PuOr = linearFromLut({ name: "PuOr", lut: data.PUOR_11_LUT });
/** PuOr_10 (diverging, discrete) */
export const PuOr_10 = discreteFromRgbLut("PuOr_10", data.PUOR_10_LUT);
/** PuOr_11 (diverging, discrete) */
export const PuOr_11 = discreteFromRgbLut("PuOr_11", data.PUOR_11_LUT);
/** PuOr_3 (diverging, discrete) */
export const PuOr_3 = discreteFromRgbLut("PuOr_3", data.PUOR_3_LUT);
/** PuOr_4 (diverging, discrete) */
export const PuOr_4 = discreteFromRgbLut("PuOr_4", data.PUOR_4_LUT);
/** PuOr_5 (diverging, discrete) */
export const PuOr_5 = discreteFromRgbLut("PuOr_5", data.PUOR_5_LUT);
/** PuOr_6 (diverging, discrete) */
export const PuOr_6 = discreteFromRgbLut("PuOr_6", data.PUOR_6_LUT);
/** PuOr_7 (diverging, discrete) */
export const PuOr_7 = discreteFromRgbLut("PuOr_7", data.PUOR_7_LUT);
/** PuOr_8 (diverging, discrete) */
export const PuOr_8 = discreteFromRgbLut("PuOr_8", data.PUOR_8_LUT);
/** PuOr_9 (diverging, discrete) */
export const PuOr_9 = discreteFromRgbLut("PuOr_9", data.PUOR_9_LUT);
/** PuRd (sequential) */
export const PuRd = linearFromLut({ name: "PuRd", lut: data.PURD_9_LUT });
/** PuRd_3 (sequential, discrete) */
export const PuRd_3 = discreteFromRgbLut("PuRd_3", data.PURD_3_LUT);
/** PuRd_4 (sequential, discrete) */
export const PuRd_4 = discreteFromRgbLut("PuRd_4", data.PURD_4_LUT);
/** PuRd_5 (sequential, discrete) */
export const PuRd_5 = discreteFromRgbLut("PuRd_5", data.PURD_5_LUT);
/** PuRd_6 (sequential, discrete) */
export const PuRd_6 = discreteFromRgbLut("PuRd_6", data.PURD_6_LUT);
/** PuRd_7 (sequential, discrete) */
export const PuRd_7 = discreteFromRgbLut("PuRd_7", data.PURD_7_LUT);
/** PuRd_8 (sequential, discrete) */
export const PuRd_8 = discreteFromRgbLut("PuRd_8", data.PURD_8_LUT);
/** PuRd_9 (sequential, discrete) */
export const PuRd_9 = discreteFromRgbLut("PuRd_9", data.PURD_9_LUT);
/** Purples (sequential) */
export const Purples = linearFromLut({ name: "Purples", lut: data.PURPLES_9_LUT });
/** Purples_3 (sequential, discrete) */
export const Purples_3 = discreteFromRgbLut("Purples_3", data.PURPLES_3_LUT);
/** Purples_4 (sequential, discrete) */
export const Purples_4 = discreteFromRgbLut("Purples_4", data.PURPLES_4_LUT);
/** Purples_5 (sequential, discrete) */
export const Purples_5 = discreteFromRgbLut("Purples_5", data.PURPLES_5_LUT);
/** Purples_6 (sequential, discrete) */
export const Purples_6 = discreteFromRgbLut("Purples_6", data.PURPLES_6_LUT);
/** Purples_7 (sequential, discrete) */
export const Purples_7 = discreteFromRgbLut("Purples_7", data.PURPLES_7_LUT);
/** Purples_8 (sequential, discrete) */
export const Purples_8 = discreteFromRgbLut("Purples_8", data.PURPLES_8_LUT);
/** Purples_9 (sequential, discrete) */
export const Purples_9 = discreteFromRgbLut("Purples_9", data.PURPLES_9_LUT);
/** RdBu (diverging) */
export const RdBu = linearFromLut({ name: "RdBu", lut: data.RDBU_11_LUT });
/** RdBu_10 (diverging, discrete) */
export const RdBu_10 = discreteFromRgbLut("RdBu_10", data.RDBU_10_LUT);
/** RdBu_11 (diverging, discrete) */
export const RdBu_11 = discreteFromRgbLut("RdBu_11", data.RDBU_11_LUT);
/** RdBu_3 (diverging, discrete) */
export const RdBu_3 = discreteFromRgbLut("RdBu_3", data.RDBU_3_LUT);
/** RdBu_4 (diverging, discrete) */
export const RdBu_4 = discreteFromRgbLut("RdBu_4", data.RDBU_4_LUT);
/** RdBu_5 (diverging, discrete) */
export const RdBu_5 = discreteFromRgbLut("RdBu_5", data.RDBU_5_LUT);
/** RdBu_6 (diverging, discrete) */
export const RdBu_6 = discreteFromRgbLut("RdBu_6", data.RDBU_6_LUT);
/** RdBu_7 (diverging, discrete) */
export const RdBu_7 = discreteFromRgbLut("RdBu_7", data.RDBU_7_LUT);
/** RdBu_8 (diverging, discrete) */
export const RdBu_8 = discreteFromRgbLut("RdBu_8", data.RDBU_8_LUT);
/** RdBu_9 (diverging, discrete) */
export const RdBu_9 = discreteFromRgbLut("RdBu_9", data.RDBU_9_LUT);
/** RdGy (diverging) */
export const RdGy = linearFromLut({ name: "RdGy", lut: data.RDGY_11_LUT });
/** RdGy_10 (diverging, discrete) */
export const RdGy_10 = discreteFromRgbLut("RdGy_10", data.RDGY_10_LUT);
/** RdGy_11 (diverging, discrete) */
export const RdGy_11 = discreteFromRgbLut("RdGy_11", data.RDGY_11_LUT);
/** RdGy_3 (diverging, discrete) */
export const RdGy_3 = discreteFromRgbLut("RdGy_3", data.RDGY_3_LUT);
/** RdGy_4 (diverging, discrete) */
export const RdGy_4 = discreteFromRgbLut("RdGy_4", data.RDGY_4_LUT);
/** RdGy_5 (diverging, discrete) */
export const RdGy_5 = discreteFromRgbLut("RdGy_5", data.RDGY_5_LUT);
/** RdGy_6 (diverging, discrete) */
export const RdGy_6 = discreteFromRgbLut("RdGy_6", data.RDGY_6_LUT);
/** RdGy_7 (diverging, discrete) */
export const RdGy_7 = discreteFromRgbLut("RdGy_7", data.RDGY_7_LUT);
/** RdGy_8 (diverging, discrete) */
export const RdGy_8 = discreteFromRgbLut("RdGy_8", data.RDGY_8_LUT);
/** RdGy_9 (diverging, discrete) */
export const RdGy_9 = discreteFromRgbLut("RdGy_9", data.RDGY_9_LUT);
/** RdPu (sequential) */
export const RdPu = linearFromLut({ name: "RdPu", lut: data.RDPU_9_LUT });
/** RdPu_3 (sequential, discrete) */
export const RdPu_3 = discreteFromRgbLut("RdPu_3", data.RDPU_3_LUT);
/** RdPu_4 (sequential, discrete) */
export const RdPu_4 = discreteFromRgbLut("RdPu_4", data.RDPU_4_LUT);
/** RdPu_5 (sequential, discrete) */
export const RdPu_5 = discreteFromRgbLut("RdPu_5", data.RDPU_5_LUT);
/** RdPu_6 (sequential, discrete) */
export const RdPu_6 = discreteFromRgbLut("RdPu_6", data.RDPU_6_LUT);
/** RdPu_7 (sequential, discrete) */
export const RdPu_7 = discreteFromRgbLut("RdPu_7", data.RDPU_7_LUT);
/** RdPu_8 (sequential, discrete) */
export const RdPu_8 = discreteFromRgbLut("RdPu_8", data.RDPU_8_LUT);
/** RdPu_9 (sequential, discrete) */
export const RdPu_9 = discreteFromRgbLut("RdPu_9", data.RDPU_9_LUT);
/** RdYlBu (diverging) */
export const RdYlBu = linearFromLut({ name: "RdYlBu", lut: data.RDYLBU_11_LUT });
/** RdYlBu_10 (diverging, discrete) */
export const RdYlBu_10 = discreteFromRgbLut("RdYlBu_10", data.RDYLBU_10_LUT);
/** RdYlBu_11 (diverging, discrete) */
export const RdYlBu_11 = discreteFromRgbLut("RdYlBu_11", data.RDYLBU_11_LUT);
/** RdYlBu_3 (diverging, discrete) */
export const RdYlBu_3 = discreteFromRgbLut("RdYlBu_3", data.RDYLBU_3_LUT);
/** RdYlBu_4 (diverging, discrete) */
export const RdYlBu_4 = discreteFromRgbLut("RdYlBu_4", data.RDYLBU_4_LUT);
/** RdYlBu_5 (diverging, discrete) */
export const RdYlBu_5 = discreteFromRgbLut("RdYlBu_5", data.RDYLBU_5_LUT);
/** RdYlBu_6 (diverging, discrete) */
export const RdYlBu_6 = discreteFromRgbLut("RdYlBu_6", data.RDYLBU_6_LUT);
/** RdYlBu_7 (diverging, discrete) */
export const RdYlBu_7 = discreteFromRgbLut("RdYlBu_7", data.RDYLBU_7_LUT);
/** RdYlBu_8 (diverging, discrete) */
export const RdYlBu_8 = discreteFromRgbLut("RdYlBu_8", data.RDYLBU_8_LUT);
/** RdYlBu_9 (diverging, discrete) */
export const RdYlBu_9 = discreteFromRgbLut("RdYlBu_9", data.RDYLBU_9_LUT);
/** RdYlGn (diverging) */
export const RdYlGn = linearFromLut({ name: "RdYlGn", lut: data.RDYLGN_11_LUT });
/** RdYlGn_10 (diverging, discrete) */
export const RdYlGn_10 = discreteFromRgbLut("RdYlGn_10", data.RDYLGN_10_LUT);
/** RdYlGn_11 (diverging, discrete) */
export const RdYlGn_11 = discreteFromRgbLut("RdYlGn_11", data.RDYLGN_11_LUT);
/** RdYlGn_3 (diverging, discrete) */
export const RdYlGn_3 = discreteFromRgbLut("RdYlGn_3", data.RDYLGN_3_LUT);
/** RdYlGn_4 (diverging, discrete) */
export const RdYlGn_4 = discreteFromRgbLut("RdYlGn_4", data.RDYLGN_4_LUT);
/** RdYlGn_5 (diverging, discrete) */
export const RdYlGn_5 = discreteFromRgbLut("RdYlGn_5", data.RDYLGN_5_LUT);
/** RdYlGn_6 (diverging, discrete) */
export const RdYlGn_6 = discreteFromRgbLut("RdYlGn_6", data.RDYLGN_6_LUT);
/** RdYlGn_7 (diverging, discrete) */
export const RdYlGn_7 = discreteFromRgbLut("RdYlGn_7", data.RDYLGN_7_LUT);
/** RdYlGn_8 (diverging, discrete) */
export const RdYlGn_8 = discreteFromRgbLut("RdYlGn_8", data.RDYLGN_8_LUT);
/** RdYlGn_9 (diverging, discrete) */
export const RdYlGn_9 = discreteFromRgbLut("RdYlGn_9", data.RDYLGN_9_LUT);
/** Reds (sequential) */
export const Reds = linearFromLut({ name: "Reds", lut: data.REDS_9_LUT });
/** Reds_3 (sequential, discrete) */
export const Reds_3 = discreteFromRgbLut("Reds_3", data.REDS_3_LUT);
/** Reds_4 (sequential, discrete) */
export const Reds_4 = discreteFromRgbLut("Reds_4", data.REDS_4_LUT);
/** Reds_5 (sequential, discrete) */
export const Reds_5 = discreteFromRgbLut("Reds_5", data.REDS_5_LUT);
/** Reds_6 (sequential, discrete) */
export const Reds_6 = discreteFromRgbLut("Reds_6", data.REDS_6_LUT);
/** Reds_7 (sequential, discrete) */
export const Reds_7 = discreteFromRgbLut("Reds_7", data.REDS_7_LUT);
/** Reds_8 (sequential, discrete) */
export const Reds_8 = discreteFromRgbLut("Reds_8", data.REDS_8_LUT);
/** Reds_9 (sequential, discrete) */
export const Reds_9 = discreteFromRgbLut("Reds_9", data.REDS_9_LUT);
/** Set1 (qualitative, discrete) */
export const Set1 = discreteFromRgbLut("Set1", data.SET1_9_LUT);
/** Set1_3 (qualitative, discrete) */
export const Set1_3 = discreteFromRgbLut("Set1_3", data.SET1_3_LUT);
/** Set1_4 (qualitative, discrete) */
export const Set1_4 = discreteFromRgbLut("Set1_4", data.SET1_4_LUT);
/** Set1_5 (qualitative, discrete) */
export const Set1_5 = discreteFromRgbLut("Set1_5", data.SET1_5_LUT);
/** Set1_6 (qualitative, discrete) */
export const Set1_6 = discreteFromRgbLut("Set1_6", data.SET1_6_LUT);
/** Set1_7 (qualitative, discrete) */
export const Set1_7 = discreteFromRgbLut("Set1_7", data.SET1_7_LUT);
/** Set1_8 (qualitative, discrete) */
export const Set1_8 = discreteFromRgbLut("Set1_8", data.SET1_8_LUT);
/** Set1_9 (qualitative, discrete) */
export const Set1_9 = discreteFromRgbLut("Set1_9", data.SET1_9_LUT);
/** Set2 (qualitative, discrete) */
export const Set2 = discreteFromRgbLut("Set2", data.SET2_8_LUT);
/** Set2_3 (qualitative, discrete) */
export const Set2_3 = discreteFromRgbLut("Set2_3", data.SET2_3_LUT);
/** Set2_4 (qualitative, discrete) */
export const Set2_4 = discreteFromRgbLut("Set2_4", data.SET2_4_LUT);
/** Set2_5 (qualitative, discrete) */
export const Set2_5 = discreteFromRgbLut("Set2_5", data.SET2_5_LUT);
/** Set2_6 (qualitative, discrete) */
export const Set2_6 = discreteFromRgbLut("Set2_6", data.SET2_6_LUT);
/** Set2_7 (qualitative, discrete) */
export const Set2_7 = discreteFromRgbLut("Set2_7", data.SET2_7_LUT);
/** Set2_8 (qualitative, discrete) */
export const Set2_8 = discreteFromRgbLut("Set2_8", data.SET2_8_LUT);
/** Set3 (qualitative, discrete) */
export const Set3 = discreteFromRgbLut("Set3", data.SET3_12_LUT);
/** Set3_10 (qualitative, discrete) */
export const Set3_10 = discreteFromRgbLut("Set3_10", data.SET3_10_LUT);
/** Set3_11 (qualitative, discrete) */
export const Set3_11 = discreteFromRgbLut("Set3_11", data.SET3_11_LUT);
/** Set3_12 (qualitative, discrete) */
export const Set3_12 = discreteFromRgbLut("Set3_12", data.SET3_12_LUT);
/** Set3_3 (qualitative, discrete) */
export const Set3_3 = discreteFromRgbLut("Set3_3", data.SET3_3_LUT);
/** Set3_4 (qualitative, discrete) */
export const Set3_4 = discreteFromRgbLut("Set3_4", data.SET3_4_LUT);
/** Set3_5 (qualitative, discrete) */
export const Set3_5 = discreteFromRgbLut("Set3_5", data.SET3_5_LUT);
/** Set3_6 (qualitative, discrete) */
export const Set3_6 = discreteFromRgbLut("Set3_6", data.SET3_6_LUT);
/** Set3_7 (qualitative, discrete) */
export const Set3_7 = discreteFromRgbLut("Set3_7", data.SET3_7_LUT);
/** Set3_8 (qualitative, discrete) */
export const Set3_8 = discreteFromRgbLut("Set3_8", data.SET3_8_LUT);
/** Set3_9 (qualitative, discrete) */
export const Set3_9 = discreteFromRgbLut("Set3_9", data.SET3_9_LUT);
/** Spectral (diverging) */
export const Spectral = linearFromLut({ name: "Spectral", lut: data.SPECTRAL_11_LUT });
/** Spectral_10 (diverging, discrete) */
export const Spectral_10 = discreteFromRgbLut("Spectral_10", data.SPECTRAL_10_LUT);
/** Spectral_11 (diverging, discrete) */
export const Spectral_11 = discreteFromRgbLut("Spectral_11", data.SPECTRAL_11_LUT);
/** Spectral_3 (diverging, discrete) */
export const Spectral_3 = discreteFromRgbLut("Spectral_3", data.SPECTRAL_3_LUT);
/** Spectral_4 (diverging, discrete) */
export const Spectral_4 = discreteFromRgbLut("Spectral_4", data.SPECTRAL_4_LUT);
/** Spectral_5 (diverging, discrete) */
export const Spectral_5 = discreteFromRgbLut("Spectral_5", data.SPECTRAL_5_LUT);
/** Spectral_6 (diverging, discrete) */
export const Spectral_6 = discreteFromRgbLut("Spectral_6", data.SPECTRAL_6_LUT);
/** Spectral_7 (diverging, discrete) */
export const Spectral_7 = discreteFromRgbLut("Spectral_7", data.SPECTRAL_7_LUT);
/** Spectral_8 (diverging, discrete) */
export const Spectral_8 = discreteFromRgbLut("Spectral_8", data.SPECTRAL_8_LUT);
/** Spectral_9 (diverging, discrete) */
export const Spectral_9 = discreteFromRgbLut("Spectral_9", data.SPECTRAL_9_LUT);
/** YlGn (sequential) */
export const YlGn = linearFromLut({ name: "YlGn", lut: data.YLGN_9_LUT });
/** YlGnBu (sequential) */
export const YlGnBu = linearFromLut({ name: "YlGnBu", lut: data.YLGNBU_9_LUT });
/** YlGnBu_3 (sequential, discrete) */
export const YlGnBu_3 = discreteFromRgbLut("YlGnBu_3", data.YLGNBU_3_LUT);
/** YlGnBu_4 (sequential, discrete) */
export const YlGnBu_4 = discreteFromRgbLut("YlGnBu_4", data.YLGNBU_4_LUT);
/** YlGnBu_5 (sequential, discrete) */
export const YlGnBu_5 = discreteFromRgbLut("YlGnBu_5", data.YLGNBU_5_LUT);
/** YlGnBu_6 (sequential, discrete) */
export const YlGnBu_6 = discreteFromRgbLut("YlGnBu_6", data.YLGNBU_6_LUT);
/** YlGnBu_7 (sequential, discrete) */
export const YlGnBu_7 = discreteFromRgbLut("YlGnBu_7", data.YLGNBU_7_LUT);
/** YlGnBu_8 (sequential, discrete) */
export const YlGnBu_8 = discreteFromRgbLut("YlGnBu_8", data.YLGNBU_8_LUT);
/** YlGnBu_9 (sequential, discrete) */
export const YlGnBu_9 = discreteFromRgbLut("YlGnBu_9", data.YLGNBU_9_LUT);
/** YlGn_3 (sequential, discrete) */
export const YlGn_3 = discreteFromRgbLut("YlGn_3", data.YLGN_3_LUT);
/** YlGn_4 (sequential, discrete) */
export const YlGn_4 = discreteFromRgbLut("YlGn_4", data.YLGN_4_LUT);
/** YlGn_5 (sequential, discrete) */
export const YlGn_5 = discreteFromRgbLut("YlGn_5", data.YLGN_5_LUT);
/** YlGn_6 (sequential, discrete) */
export const YlGn_6 = discreteFromRgbLut("YlGn_6", data.YLGN_6_LUT);
/** YlGn_7 (sequential, discrete) */
export const YlGn_7 = discreteFromRgbLut("YlGn_7", data.YLGN_7_LUT);
/** YlGn_8 (sequential, discrete) */
export const YlGn_8 = discreteFromRgbLut("YlGn_8", data.YLGN_8_LUT);
/** YlGn_9 (sequential, discrete) */
export const YlGn_9 = discreteFromRgbLut("YlGn_9", data.YLGN_9_LUT);
/** YlOrBr (sequential) */
export const YlOrBr = linearFromLut({ name: "YlOrBr", lut: data.YLORBR_9_LUT });
/** YlOrBr_3 (sequential, discrete) */
export const YlOrBr_3 = discreteFromRgbLut("YlOrBr_3", data.YLORBR_3_LUT);
/** YlOrBr_4 (sequential, discrete) */
export const YlOrBr_4 = discreteFromRgbLut("YlOrBr_4", data.YLORBR_4_LUT);
/** YlOrBr_5 (sequential, discrete) */
export const YlOrBr_5 = discreteFromRgbLut("YlOrBr_5", data.YLORBR_5_LUT);
/** YlOrBr_6 (sequential, discrete) */
export const YlOrBr_6 = discreteFromRgbLut("YlOrBr_6", data.YLORBR_6_LUT);
/** YlOrBr_7 (sequential, discrete) */
export const YlOrBr_7 = discreteFromRgbLut("YlOrBr_7", data.YLORBR_7_LUT);
/** YlOrBr_8 (sequential, discrete) */
export const YlOrBr_8 = discreteFromRgbLut("YlOrBr_8", data.YLORBR_8_LUT);
/** YlOrBr_9 (sequential, discrete) */
export const YlOrBr_9 = discreteFromRgbLut("YlOrBr_9", data.YLORBR_9_LUT);
/** YlOrRd (sequential) */
export const YlOrRd = linearFromLut({ name: "YlOrRd", lut: data.YLORRD_9_LUT });
/** YlOrRd_3 (sequential, discrete) */
export const YlOrRd_3 = discreteFromRgbLut("YlOrRd_3", data.YLORRD_3_LUT);
/** YlOrRd_4 (sequential, discrete) */
export const YlOrRd_4 = discreteFromRgbLut("YlOrRd_4", data.YLORRD_4_LUT);
/** YlOrRd_5 (sequential, discrete) */
export const YlOrRd_5 = discreteFromRgbLut("YlOrRd_5", data.YLORRD_5_LUT);
/** YlOrRd_6 (sequential, discrete) */
export const YlOrRd_6 = discreteFromRgbLut("YlOrRd_6", data.YLORRD_6_LUT);
/** YlOrRd_7 (sequential, discrete) */
export const YlOrRd_7 = discreteFromRgbLut("YlOrRd_7", data.YLORRD_7_LUT);
/** YlOrRd_8 (sequential, discrete) */
export const YlOrRd_8 = discreteFromRgbLut("YlOrRd_8", data.YLORRD_8_LUT);
/** YlOrRd_9 (sequential, discrete) */
export const YlOrRd_9 = discreteFromRgbLut("YlOrRd_9", data.YLORRD_9_LUT);
