// Generated by scripts/import-cmap-glasbey.mjs. Do not edit by hand.

import { linearFromLut } from "../build";
import * as data from "../data/glasbey.generated";

export const glasbey = linearFromLut({ name: "glasbey", lut: data.GLASBEY_LUT });
