// Generated by scripts/import-cmap-google.mjs. Do not edit by hand.

import { linearFromLut } from "../build";
import * as data from "../data/google.generated";

export const turbo = linearFromLut({ name: "turbo", lut: data.TURBO_LUT });
