// Generated by scripts/import-cmap-imagej.mjs. Do not edit by hand.

import { linearFromLut } from "../build";
import { linearColormap } from "../linear";
import type { ColorStop } from "../types";
import * as data from "../data/imagej.generated";

function stopsFromPositionedLut(pos: Float32Array, lut: Float32Array): ColorStop[] {
  const out: ColorStop[] = Array.from({ length: pos.length });
  for (let i = 0; i < pos.length; i++) {
    const o = i * 3;
    out[i] = {
      position: pos[i],
      color: { r: lut[o], g: lut[o + 1], b: lut[o + 2], alpha: 1 },
    };
  }
  return out;
}

export const GreenFireBlue = linearFromLut({ name: "GreenFireBlue", lut: data.GREENFIREBLUE_LUT });
export const HiLo = linearColormap({
  name: "HiLo",
  stops: stopsFromPositionedLut(data.HILO_POS, data.HILO_LUT),
});
export const fire = linearFromLut({ name: "fire", lut: data.FIRE_LUT });
export const ice = linearFromLut({ name: "ice", lut: data.ICE_LUT });
