// Generated by scripts/import-cmap-matlab.mjs. Do not edit by hand.

import { linearFromLut } from "../build";
import { linearColormap } from "../linear";
import type { ColorStop } from "../types";
import * as data from "../data/matlab.generated";

function stopsFromPositionedLut(pos: Float32Array, lut: Float32Array): ColorStop[] {
  const out: ColorStop[] = Array.from({ length: pos.length });
  for (let i = 0; i < pos.length; i++) {
    const o = i * 3;
    out[i] = {
      position: pos[i],
      color: { r: lut[o], g: lut[o + 1], b: lut[o + 2], alpha: 1 },
    };
  }
  return out;
}

export const autumn = linearFromLut({ name: "autumn", lut: data.AUTUMN_LUT });
export const bone = linearColormap({
  name: "bone",
  stops: stopsFromPositionedLut(data.BONE_POS, data.BONE_LUT),
});
export const cool = linearFromLut({ name: "cool", lut: data.COOL_LUT });
export const copper = linearColormap({
  name: "copper",
  stops: stopsFromPositionedLut(data.COPPER_POS, data.COPPER_LUT),
});
export const gray = linearFromLut({ name: "gray", lut: data.GRAY_LUT });
export const hot = linearColormap({
  name: "hot",
  stops: stopsFromPositionedLut(data.HOT_POS, data.HOT_LUT),
});
export const hsv = linearColormap({
  name: "hsv",
  stops: stopsFromPositionedLut(data.HSV_POS, data.HSV_LUT),
});
export const jet = linearColormap({
  name: "jet",
  stops: stopsFromPositionedLut(data.JET_POS, data.JET_LUT),
});
export const pink = linearFromLut({ name: "pink", lut: data.PINK_LUT });
export const spring = linearFromLut({ name: "spring", lut: data.SPRING_LUT });
export const summer = linearFromLut({ name: "summer", lut: data.SUMMER_LUT });
export const winter = linearFromLut({ name: "winter", lut: data.WINTER_LUT });
