// Generated by scripts/import-cmap-matplotlib.mjs. Do not edit by hand.

import { linearFromLut } from "../build";
import { linearColormap } from "../linear";
import type { ColorStop } from "../types";
import * as data from "../data/matplotlib.generated";

function stopsFromPositionedLut(pos: Float32Array, lut: Float32Array): ColorStop[] {
  const out: ColorStop[] = Array.from({ length: pos.length });
  for (let i = 0; i < pos.length; i++) {
    const o = i * 3;
    out[i] = {
      position: pos[i],
      color: { r: lut[o], g: lut[o + 1], b: lut[o + 2], alpha: 1 },
    };
  }
  return out;
}

export const CMRmap = linearFromLut({ name: "CMRmap", lut: data.CMRMAP_LUT });
export const Wistia = linearFromLut({ name: "Wistia", lut: data.WISTIA_LUT });
export const binary = linearFromLut({ name: "binary", lut: data.BINARY_LUT });
export const brg = linearFromLut({ name: "brg", lut: data.BRG_LUT });
export const bwr = linearFromLut({ name: "bwr", lut: data.BWR_LUT });
export const coolwarm = linearColormap({
  name: "coolwarm",
  stops: stopsFromPositionedLut(data.COOLWARM_POS, data.COOLWARM_LUT),
});
export const nipy_spectral = linearFromLut({ name: "nipy_spectral", lut: data.NIPY_SPECTRAL_LUT });
export const seismic = linearFromLut({ name: "seismic", lut: data.SEISMIC_LUT });
export const terrain = linearColormap({
  name: "terrain",
  stops: stopsFromPositionedLut(data.TERRAIN_POS, data.TERRAIN_LUT),
});
export const twilight = linearFromLut({ name: "twilight", lut: data.TWILIGHT_LUT });
export const twilight_shifted = linearFromLut({ name: "twilight_shifted", lut: data.TWILIGHT_SHIFTED_LUT });
