// Generated by scripts/import-cmap-observable.mjs. Do not edit by hand.

import { discreteFromRgbLut } from "../build";
import * as data from "../data/observable.generated";

export const observable10 = discreteFromRgbLut("observable10", data.OBSERVABLE10_LUT);
