// Generated by scripts/import-cmap-okabeito.mjs. Do not edit by hand.

import { discreteFromRgbLut } from "../build";
import * as data from "../data/okabeito.generated";

export const okabeito = discreteFromRgbLut("okabeito", data.OKABEITO_LUT);
