// Generated by scripts/import-cmap-paraview.mjs. Do not edit by hand.

import { linearFromLut } from "../build";
import * as data from "../data/paraview.generated";

export const blackbody = linearFromLut({ name: "blackbody", lut: data.BLACKBODY_LUT });
export const coolwarm = linearFromLut({ name: "coolwarm", lut: data.COOLWARM_LUT });
export const fast = linearFromLut({ name: "fast", lut: data.FAST_LUT });
export const kindlmann = linearFromLut({ name: "kindlmann", lut: data.KINDLMANN_LUT });
