// Generated by scripts/import-cmap-petroff.mjs. Do not edit by hand.

import { discreteFromRgbLut } from "../build";
import * as data from "../data/petroff.generated";

export const petroff10 = discreteFromRgbLut("petroff10", data.PETROFF10_LUT);
export const petroff6 = discreteFromRgbLut("petroff6", data.PETROFF6_LUT);
export const petroff8 = discreteFromRgbLut("petroff8", data.PETROFF8_LUT);
