// Generated by scripts/import-cmap-seaborn.mjs. Do not edit by hand.

import { linearFromLut } from "../build";
import * as data from "../data/seaborn.generated";

export const crest = linearFromLut({ name: "crest", lut: data.CREST_LUT });
export const flare = linearFromLut({ name: "flare", lut: data.FLARE_LUT });
export const icefire = linearFromLut({ name: "icefire", lut: data.ICEFIRE_LUT });
export const mako = linearFromLut({ name: "mako", lut: data.MAKO_LUT });
export const rocket = linearFromLut({ name: "rocket", lut: data.ROCKET_LUT });
export const vlag = linearFromLut({ name: "vlag", lut: data.VLAG_LUT });
