// Generated by scripts/import-cmap-yorick.mjs. Do not edit by hand.

import { linearFromLut } from "../build";
import { linearColormap } from "../linear";
import type { ColorStop } from "../types";
import * as data from "../data/yorick.generated";

function stopsFromPositionedLut(pos: Float32Array, lut: Float32Array): ColorStop[] {
  const out: ColorStop[] = Array.from({ length: pos.length });
  for (let i = 0; i < pos.length; i++) {
    const o = i * 3;
    out[i] = {
      position: pos[i],
      color: { r: lut[o], g: lut[o + 1], b: lut[o + 2], alpha: 1 },
    };
  }
  return out;
}

export const earth = linearColormap({
  name: "earth",
  stops: stopsFromPositionedLut(data.EARTH_POS, data.EARTH_LUT),
});
export const ncar = linearColormap({
  name: "ncar",
  stops: stopsFromPositionedLut(data.NCAR_POS, data.NCAR_LUT),
});
export const rainbow = linearColormap({
  name: "rainbow",
  stops: stopsFromPositionedLut(data.RAINBOW_POS, data.RAINBOW_LUT),
});
export const stern = linearColormap({
  name: "stern",
  stops: stopsFromPositionedLut(data.STERN_POS, data.STERN_LUT),
});
export const yarg = linearFromLut({ name: "yarg", lut: data.YARG_LUT });
