// Generated by scripts/import-cmap-ibm.mjs. Do not edit by hand.

import { discreteFromRgbLut } from "../build";
import * as data from "../data/ibm.generated";

export const ibm_dark = discreteFromRgbLut("ibm_dark", data.IBM_DARK_LUT);
export const ibm_light = discreteFromRgbLut("ibm_light", data.IBM_LIGHT_LUT);
