// Generated by scripts/import-cmap-napari.mjs. Do not edit by hand.

import { linearFromLut } from "../build";
import * as data from "../data/napari.generated";

export const HiLo = linearFromLut({ name: "HiLo", lut: data.HILO_LUT });
export const nan = linearFromLut({ name: "nan", lut: data.NAN_LUT });
