// Generated by scripts/import-cmap-vispy.mjs. Do not edit by hand.

import { linearFromLut } from "../build";
import { linearColormap } from "../linear";
import type { ColorStop } from "../types";
import * as data from "../data/vispy.generated";

function stopsFromPositionedLut(pos: Float32Array, lut: Float32Array): ColorStop[] {
  const out: ColorStop[] = Array.from({ length: pos.length });
  for (let i = 0; i < pos.length; i++) {
    const o = i * 3;
    out[i] = {
      position: pos[i],
      color: { r: lut[o], g: lut[o + 1], b: lut[o + 2], alpha: 1 },
    };
  }
  return out;
}

export const GrBu = linearFromLut({ name: "GrBu", lut: data.GRBU_LUT });
export const GrBu_d = linearFromLut({ name: "GrBu_d", lut: data.GRBU_D_LUT });
export const PuGr = linearFromLut({ name: "PuGr", lut: data.PUGR_LUT });
export const RdBu = linearFromLut({ name: "RdBu", lut: data.RDBU_LUT });
export const RdYeBuCy = linearColormap({
  name: "RdYeBuCy",
  stops: stopsFromPositionedLut(data.RDYEBUCY_POS, data.RDYEBUCY_LUT),
});
export const diverging = linearFromLut({ name: "diverging", lut: data.DIVERGING_LUT });
export const hsl = linearFromLut({ name: "hsl", lut: data.HSL_LUT });
export const husl = linearFromLut({ name: "husl", lut: data.HUSL_LUT });
export const ice = linearFromLut({ name: "ice", lut: data.ICE_LUT });
export const light_blues = linearFromLut({ name: "light_blues", lut: data.LIGHT_BLUES_LUT });
export const orange = linearFromLut({ name: "orange", lut: data.ORANGE_LUT });
