[build-system]
build-backend = "hatchling.build"
requires = [ "hatchling", "uv-dynamic-versioning" ]

[project]
name = "nd-embedding-atlas"
description = "An interactive browser-based dashboard linking AI embeddings to source nD image data for rapid exploration and annotation."
readme = "README.md"
license = { file = "LICENSE" }
maintainers = [
  { name = "Sricharan Reddy Varra", email = "sricharan.varra@biohub.org" },
]
authors = [ { name = "Sricharan Reddy Varra" } ]
requires-python = ">=3.12,<3.14"
classifiers = [
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
]
dynamic = [ "version" ]
dependencies = [
  "annbatch>=0.0.7",
  "anndata>=0.12.9",
  "cmap>=0.5",
  "dask[dataframe,distributed]>=2025.9.2",
  "duckdb>=1.4.4",
  "fastapi>=0.128",
  "gunicorn>=25",
  "iohub",
  "mudata>=0.3.4",
  "obstore>=0.8.2",
  "pyarrow>=18",
  "pyyaml>=6",
  "rich>=14.3.1",
  "scanpy>=1.11.5",
  "session-info2",
  "sse-starlette>=3.3.4",
  "structlog>=25.5",
  "typer>=0.21.1",
  "uvicorn>=0.34",
  "zarr>=3.1.5",
  "zarrs>=0.2.1",
]
# https://docs.pypi.org/project_metadata/#project-urls
urls.Documentation = "https://super-adventure-yv3eleq.pages.github.io/"
urls.Homepage = "https://github.com/czbiohub-sf/nd-embedding-atlas"
urls.Source = "https://github.com/czbiohub-sf/nd-embedding-atlas"
scripts.nd-embedding-atlas = "nd_embedding_atlas.cli._app:app"
scripts.ndea = "nd_embedding_atlas.cli._app:app"
scripts.ndimg = "nd_embedding_atlas.cli._ndimg:app"

[dependency-groups]
dev = [
  "pyinstrument>=5.1.2",
  { include-group = "doc" },
  { include-group = "test" },
]
test = [
  "coverage>=7.13.2",
  "httpx>=0.27",
  "pytest>=9.0.2",
  "pytest-cov>=7",
]
doc = [
  "ipykernel",
  "mike",
  "pymdown-extensions>=10.20.1",
  "zensical>=0.0.21",
]
neuroglancer = [
  "neuroglancer>=2.40",
  "numpy",
]

[tool.hatch]
# Uses hatch_build.py at project root

build.artifacts = [ "src/nd_embedding_atlas/_frontend" ]
build.hooks.custom = { "enable-by-default" = false }
envs.default.installer = "uv"
envs.default.dependency-groups = [ "dev" ]
envs.docs.dependency-groups = [ "doc" ]
envs.docs.scripts.build = "sphinx-build -M html docs docs/_build -W {args}"
envs.docs.scripts.open = "python -m webbrowser -t docs/_build/html/index.html"
envs.docs.scripts.clean = "git clean -fdX -- {args:docs}"
envs.hatch-test.dependency-groups = [ "test" ]
envs.hatch-test.matrix = [
  # Test the lowest and highest supported Python versions with normal deps
  { deps = [ "stable" ], python = [ "3.12", "3.13" ] },
  # Test the newest supported Python version also with pre-release deps
  { deps = [ "pre" ], python = [ "3.13" ] },
]
# If the matrix variable `deps` is set to "pre",
# set the environment variable `UV_PRERELEASE` to "allow".
envs.hatch-test.overrides.matrix.deps.env-vars = [
  { key = "UV_PRERELEASE", value = "allow", if = [
    "pre",
  ] },
]
version.source = "uv-dynamic-versioning"

[tool.uv.sources]
iohub = { git = "https://github.com/czbiohub-sf/iohub", branch = "main" }
mike = { git = "https://github.com/squidfunk/mike.git" }

[tool.ruff]
line-length = 120
src = [ "src" ]
extend-include = [ "*.ipynb" ]
format.docstring-code-format = true
lint.select = [
  "B",    # flake8-bugbear
  "BLE",  # flake8-blind-except
  "C4",   # flake8-comprehensions
  "D",    # pydocstyle
  "E",    # Error detected by Pycodestyle
  "F",    # Errors detected by Pyflakes
  "I",    # isort
  "NPY",  # NumPy-specific rules
  "PD",   # Pandas code
  "PERF", # Perflint
  "PT",   # Pytest
  "PTH",  # pathlib
  "RUF",  # Ruff-specific rules
  "TID",  # flake8-tidy-imports
  "TRY",  # Tryceratops
  "UP",   # pyupgrade
  "W",    # Warning detected by Pycodestyle
]
lint.ignore = [
  "B008", # Errors from function calls in argument defaults. These are fine when the result is immutable.
  "D100", # Missing docstring in public module
  "D104", # Missing docstring in public package
  "D105", # __magic__ methods are often self-explanatory, allow missing docstrings
  "D107", # Missing docstring in __init__
  # Disable one in each pair of mutually incompatible rules
  "D203", # We don’t want a blank line before a class docstring
  "D213", # <> We want docstrings to start immediately after the opening triple quote
  "D400", # first line should end with a period [Bug: doesn’t work with single-line docstrings]
  "D401", # First line should be in imperative mood; try rephrasing
  "E501", # line too long -> we accept long comment lines; formatter gets rid of long code lines
  "E731", # Do not assign a lambda expression, use a def -> lambda expression assignments are convenient
  "E741", # allow I, O, l as variable names -> I is the identity matrix
]
lint.per-file-ignores."*/__init__.py" = [ "F401" ]
lint.per-file-ignores."docs/*" = [ "I" ]
lint.per-file-ignores."tests/*" = [ "D" ]
lint.pydocstyle.convention = "numpy"

[tool.pytest]
strict = true
testpaths = [ "tests" ]
addopts = [
  "--import-mode=importlib", # allow using test files with same name
]

[tool.coverage]
run.omit = [ "**/test_*.py" ]
run.patch = [ "subprocess" ]
run.source = [ "nd_embedding_atlas" ]

[tool.cruft]
skip = [
  "tests",
  "src/**/__init__.py",
  "src/**/basic.py",
  "docs/api.md",
  "docs/changelog.md",
  "docs/references.bib",
  "docs/references.md",
  "docs/notebooks/example.ipynb",
]
