import { defineConfig } from "vite-plus";

export default defineConfig({
  // ── Oxlint ────────────────────────────────────────────────────────────────
  lint: {
    options: {
      typeAware: true,
      typeCheck: true,
    },

    // Explicitly list ALL plugins — setting "plugins" overwrites the default set.
    // React/react-perf rules only fire on JSX-bearing files, so they're safe to
    // enable globally (no noise on backend .ts).
    plugins: ["eslint", "typescript", "unicorn", "oxc", "react", "react-perf", "import"],

    // JS plugins (alpha) — ESLint plugins loaded by Oxlint. Required for
    // TypeGPU `'use gpu'` rules (no Rust port).
    jsPlugins: ["eslint-plugin-typegpu"],

    env: {
      browser: true,
      builtin: true,
    },

    settings: {
      react: { version: "19.0.0" },
    },

    ignorePatterns: [
      "**/dist/**",
      "**/node_modules/**",
      "apps/ndea/src/frontend/components/ui/**",
      "apps/ndea/src/frontend/ochre/colormap/data/**",
      // Boundary fixtures intentionally contain imports and symbols that the
      // repository gate must reject.
      "scripts/fixtures/package-boundaries/**",
      // .bunli/commands.gen.ts is regenerated by `bunx bunli generate`;
      // it carries embedded JSON literals + raw AST nodes that fmt/lint
      // would churn on every regeneration.
      ".bunli/**",
      // Design-handoff docs, critique snapshots, vendored impeccable skill.
      ".design/**",
      ".impeccable/**",
      ".github/skills/**",
    ],

    categories: {
      correctness: "error",
      suspicious: "warn",
    },

    rules: {
      // CORRECTNESS
      "no-unused-vars": "off",
      "typescript/no-unused-vars": [
        "warn",
        {
          argsIgnorePattern: "^_",
          varsIgnorePattern: "^_",
          ignoreRestSiblings: true,
        },
      ],

      // REACT HOOKS
      "react/rules-of-hooks": "error",
      "react/exhaustive-deps": "warn",
      "react/only-export-components": ["warn", { allowConstantExport: true }],
      "react/iframe-missing-sandbox": "error",

      // TYPE SAFETY
      "@typescript-eslint/no-explicit-any": "warn",
      "typescript/consistent-type-imports": ["warn", { prefer: "type-imports", fixStyle: "separate-type-imports" }],
      "typescript/no-floating-promises": "error",
      "typescript/no-misused-promises": "error",
      "typescript/return-await": "error",
      "typescript/only-throw-error": "error",
      "typescript/no-deprecated": "error",
      "typescript/no-base-to-string": "error",
      "typescript/no-misused-spread": "error",
      "typescript/no-array-delete": "error",
      "typescript/no-unsafe-enum-comparison": "error",
      "typescript/no-unsafe-function-type": "error",
      "typescript/no-non-null-asserted-nullish-coalescing": "error",
      "typescript/no-non-null-asserted-optional-chain": "error",
      "typescript/no-duplicate-type-constituents": "error",
      "typescript/no-redundant-type-constituents": "error",
      "typescript/no-import-type-side-effects": "error",
      "typescript/no-unnecessary-template-expression": "warn",
      "typescript/prefer-find": "warn",
      "typescript/no-confusing-non-null-assertion": "error",
      "typescript/no-duplicate-enum-values": "error",
      "typescript/no-unnecessary-type-conversion": "warn",
      "typescript/use-unknown-in-catch-callback-variable": "error",

      // TS MODERNIZATION
      "typescript/prefer-nullish-coalescing": "warn",
      "typescript/prefer-optional-chain": "warn",
      "typescript/no-wrapper-object-types": "error",
      "typescript/no-empty-object-type": "warn",
      "typescript/ban-ts-comment": [
        "warn",
        {
          "ts-ignore": "allow-with-description",
          "ts-expect-error": "allow-with-description",
          minimumDescriptionLength: 10,
        },
      ],
      "typescript/prefer-as-const": "warn",
      "typescript/no-unnecessary-type-assertion": "warn",

      // STYLE
      "prefer-const": "error",
      "no-console": "off",
      // Conventional `_`-prefixed private fields (AnnData class, math
      // shorthands like `l_`/`m_`/`s_` in Oklab, exhaustiveness guards
      // `const _exhaustive: never = ...`). Oxlint started enforcing this
      // after the vite-plus 0.1.22 bump; the codebase uses these patterns
      // intentionally.
      "no-underscore-dangle": "off",
      eqeqeq: ["error", "always", { null: "ignore" }],
      "no-var": "error",
      "no-eval": "error",
      "no-unsafe-finally": "error",
      "no-loop-func": "error",
      "no-useless-catch": "error",
      "no-duplicate-case": "error",

      // UNICORN
      "unicorn/prefer-includes": "warn",
      "unicorn/prefer-string-starts-ends-with": "warn",
      "unicorn/prefer-array-flat-map": "warn",
      "unicorn/prefer-negative-index": "warn",
      "unicorn/prefer-array-find": "warn",
      "unicorn/prefer-type-error": "warn",
      "unicorn/no-useless-undefined": "warn",
      "unicorn/no-null": "off",
      "unicorn/no-array-for-each": "off",
      "unicorn/filename-case": [
        "error",
        {
          cases: {
            kebabCase: true,
            pascalCase: true,
          },
          ignore: ["^use[A-Z]"],
        },
      ],

      // REACT PERFORMANCE — disabled (too many false positives on stable refs)
      "react-perf/jsx-no-new-array-as-prop": "off",
      "react-perf/jsx-no-new-object-as-prop": "off",
      "react-perf/jsx-no-new-function-as-prop": "off",
      "react-perf/jsx-no-jsx-as-prop": "off",

      // OXC
      "oxc/no-accumulating-spread": "error",
      "oxc/bad-comparison-sequence": "error",
      "oxc/missing-throw": "error",
      "oxc/bad-object-literal-comparison": "error",
      "oxc/bad-char-at-comparison": "error",
      "oxc/bad-min-max-func": "error",
      "oxc/const-comparisons": "error",
      "oxc/double-comparisons": "warn",
      "oxc/erasing-op": "warn",
      "oxc/only-used-in-recursion": "warn",

      // IMPORT HYGIENE
      "import/no-duplicates": "error",
      "import/no-self-import": "error",
      "import/no-cycle": "warn",

      // TYPEGPU (JS plugin) — WGSL-correctness rules for `'use gpu'` functions.
      "typegpu/no-integer-division": "warn",
      "typegpu/no-math": "warn",
      "typegpu/no-uninitialized-variables": "error",
      "typegpu/no-unwrapped-objects": "error",
      "typegpu/no-invalid-assignment": "error",

      // REACT JSX STYLE
      "react/jsx-fragments": ["warn", "syntax"],
      "react/jsx-boolean-value": ["warn", "never"],
      "react/no-unknown-property": "error",
      "react/no-danger": "warn",
      "react/react-in-jsx-scope": "off",
      "react/jsx-no-target-blank": "error",
      "react/jsx-key": ["error", { checkFragmentShorthand: true }],

      // TS BUG CATCHERS
      "typescript/no-for-in-array": "error",
      "typescript/consistent-type-assertions": ["warn", { assertionStyle: "as" }],

      // ASYNC CORRECTNESS
      "require-await": "error",
      "no-promise-executor-return": "error",

      // MODERNIZATION
      "prefer-template": "warn",
      "react/self-closing-comp": ["warn", { html: false }],
      "typescript/array-type": ["warn", { default: "array" }],
      "typescript/unbound-method": "off",
      "typescript/no-unsafe-type-assertion": "off",
      // Overly strict on the React useEffect cleanup-return idiom (return a
      // cleanup on the branch that needs one, otherwise fall through).
      "typescript/consistent-return": "off",
    },

    overrides: [
      {
        // nd component layer co-locates contract data with its component by
        // design (ND_ICONS registry + NdIcon, ND_PORT_KINDS + NdPort, mock
        // PRNG + mocks) — fast-refresh purity doesn't apply to this layer.
        files: ["apps/ndea/src/frontend/components/nd/**/*.tsx", "apps/ndea/src/frontend/core/workspace/**/*.tsx"],
        rules: {
          "react/only-export-components": "off",
        },
      },
      {
        // TypeGPU opaque APIs + GPU handle non-null assertions
        files: ["apps/ndea/src/frontend/scatter-gpu/**/*.ts", "apps/ndea/src/frontend/scatter-gpu/**/*.tsx"],
        rules: {
          "typescript/no-non-null-assertion": "off",
          "@typescript-eslint/no-explicit-any": "off",
          "typescript/no-floating-promises": "warn",
        },
      },
      {
        files: ["**/*.test.ts", "**/*.test.tsx", "**/*.spec.ts", "**/*.spec.tsx"],
        rules: {
          "@typescript-eslint/no-explicit-any": "off",
          "typescript/no-non-null-assertion": "off",
          "typescript/no-floating-promises": "off",
          // `bun:test`'s `expect(...).rejects` returns a thenable that
          // typescript-eslint doesn't recognise — disable the check to keep
          // the common `await expect(fn()).rejects.toThrow()` pattern working.
          "typescript/await-thenable": "off",
        },
      },
      {
        // scripts/* are one-off dev tools using bun:test or top-level await.
        // bun:test's expect(...).rejects.toThrow() is thenable at runtime but
        // typescript-eslint can't see it as a Promise via its types.
        files: ["apps/ndea/scripts/**/*.ts"],
        rules: {
          "typescript/await-thenable": "off",
          "require-await": "off",
        },
      },
      {
        // Dedicated Worker globals — `self` is a DedicatedWorkerGlobalScope,
        // so postMessage takes no targetOrigin and async event listeners are fine.
        // Also covers the main-thread call sites that post to dedicated
        // workers (crop-pool.ts, readers.ts) — same reason: no targetOrigin
        // is required for Worker postMessage, only for window postMessage.
        files: [
          "packages/zarr/src/column-worker.ts",
          "packages/zarr/src/readers.ts",
          "apps/ndea/src/server/crop-pool.ts",
          "apps/ndea/src/server/crop-worker.ts",
        ],
        rules: {
          "unicorn/require-post-message-target-origin": "off",
          "unicorn/prefer-add-event-listener": "off",
          "typescript/no-misused-promises": "off",
        },
      },
      {
        // Plugin boundary (PLUGIN-ARCHITECTURE §3, §7.6). Plugins talk to the app
        // ONLY through the injected PluginHost — never the cross-view stores or
        // the DashboardContext directly. ERROR (Phase 3): the views are converted
        // and no plugin imports a cross-view store / dashboard context, so the
        // boundary is now CI-enforced. (The reactive highlight read in
        // table/charts uses @/hooks/useDashboard, which is intentionally NOT
        // banned — it moves to a HighlightBus in Phase 4, §6.7.) The `/api/*`
        // literal ban stays enforced by the capability-gated DataApi.
        files: ["apps/ndea/src/frontend/plugins/**/*.ts", "apps/ndea/src/frontend/plugins/**/*.tsx"],
        rules: {
          "no-restricted-imports": [
            "error",
            {
              patterns: [
                {
                  group: ["@/stores/*", "**/stores/*"],
                  message:
                    "Plugins must not touch cross-view stores directly — go through the injected PluginHost (PLUGIN-ARCHITECTURE §7.6).",
                },
                {
                  group: ["@/dashboard/*", "**/dashboard/*"],
                  message: "Plugins must not import DashboardContext — read state via the PluginHost.",
                },
              ],
            },
          ],
        },
      },
      {
        // Node cross-view boundary (host-seam single-channel refactor). Node
        // bodies render inside a plugin host, so their cross-view focus/selection
        // MUST flow through the injected `host.*` (sync-group & edge-aware), never
        // the global cross-view bus hub or the cross-view selection stores. The
        // lint half of the conformance backstop (core/node/host-routing.test.ts
        // is the behavioral half).
        //
        // Also banned: the coordination plane (`@/core/coordination`) — the
        // symmetric cross-view channel (focus/viewSync/ordering scopes) is reached
        // ONLY through the host facets the body-dock seam injects, never by a node
        // importing the backbone (coordination-model plan U5); and ViewSyncStore,
        // now that `host.viewSync.subscribe` exists and scatter routes pan/zoom
        // through the seam (U2 closed that follow-up).
        //
        // NOT banned here: the render/collection/panel stores (different concern);
        // `@/hooks/useDashboard` + the DashboardContext *type* imports (still the
        // read path for non-cross-view metadata/trajectories). `components/charts`
        // (not yet under nodes/) is excluded — host-less today, still reads
        // selectionBus; its host migration is the remaining follow-up.
        files: ["apps/ndea/src/frontend/nodes/**/*.{ts,tsx}", "apps/ndea/src/frontend/scatter-gpu/**/*.{ts,tsx}"],
        rules: {
          "no-restricted-imports": [
            "error",
            {
              patterns: [
                {
                  group: [
                    "@/core/buses",
                    "**/core/buses",
                    "@/core/coordination",
                    "**/core/coordination",
                    "**/core/coordination/**",
                    "@/stores/SelectionSyncStore",
                    "**/SelectionSyncStore",
                    "@/stores/RoaringBroadcastStore",
                    "**/RoaringBroadcastStore",
                    "@/stores/ViewSyncStore",
                    "**/ViewSyncStore",
                  ],
                  message:
                    "Cross-view focus/selection/coordination in a plugin-rendered body must route through the injected host.* (host-seam single-channel refactor + coordination plane), never the global bus/store or the coordination backbone directly.",
                },
              ],
            },
          ],
        },
      },
      {
        // Node spec files (`*.node.tsx`) legitimately co-locate a small inline
        // Body / config export with the node spec (e.g. the threshold instance
        // node). Fast-refresh's only-export-components rule doesn't apply — these
        // aren't hot-edited leaf components.
        files: ["apps/ndea/src/frontend/nodes/**/node.tsx"],
        rules: { "react/only-export-components": "off" },
      },
    ],
  },

  // ── Oxfmt ──────────────────────────────────────────────────────────────────
  fmt: {
    printWidth: 120,
    tabWidth: 2,
    useTabs: false,
    semi: true,
    singleQuote: false,
    jsxSingleQuote: false,
    trailingComma: "all",
    arrowParens: "always",
    bracketSpacing: true,
    endOfLine: "lf",
    sortPackageJson: true,
    // - .bunli/commands.gen.ts is regenerated by `bunx bunli generate`
    //   and carries embedded JSON literals + raw AST nodes — fmt would
    //   rewrite shapes the generator overwrites on the next run.
    // - dist/ and site/ are build outputs (gitignored, but oxfmt still walks
    //   the working tree).
    // - zensical.toml is a doc-tool config laid out for human reading;
    //   reflowing it would fight the upstream template's comments.
    // - ochre/colormap/data/** are vendored colormap LUTs hand-packed at
    //   12 numbers per line; oxfmt's `Float32Array.of(...)` rule unpacks
    //   to one number per line, blowing the diff up by 10×.
    // - .design/** is the design-handoff doc tree (specs, vocabulary);
    //   .impeccable/** is critique snapshots; .github/skills/** is the
    //   vendored impeccable skill — none are project source.
    // - docs/presentations/** is deterministic generator output; formatting
    //   it would create drift from scripts/build-design-presentation.ts.
    ignorePatterns: [
      ".bunli/**",
      "**/dist/**",
      "site/**",
      "zensical.toml",
      "apps/ndea/src/frontend/ochre/colormap/data/**",
      ".design/**",
      ".impeccable/**",
      ".github/skills/**",
      "docs/presentations/**",
    ],
  },

  // ── Pre-commit (staged files only) ────────────────────────────────────────
  staged: {
    "apps/ndea/src/**": "vp check --fix",
    "packages/**/src/**": "vp check --fix",
  },
});
