import tailwindcss from "@tailwindcss/vite";
import react from "@vitejs/plugin-react";
import typegpuPlugin from "unplugin-typegpu/vite";
import { defineConfig } from "vite-plus";
import { devConsoleEcho } from "./scripts/dev-console-echo.ts";
import { devErrorReporter } from "./scripts/dev-error-reporter.ts";

export default defineConfig({
  // ── Oxlint ────────────────────────────────────────────────────────────────
  lint: {
    options: {
      typeAware: true,
      typeCheck: true,
    },

    // Explicitly list ALL plugins — setting "plugins" overwrites the default set.
    // React/react-perf rules only fire on JSX-bearing files, so they're safe to
    // enable globally (no noise on backend .ts).
    plugins: ["eslint", "typescript", "unicorn", "oxc", "react", "react-perf", "import"],

    // JS plugins (alpha) — ESLint plugins loaded by Oxlint. Required for
    // TypeGPU `'use gpu'` rules (no Rust port).
    jsPlugins: ["eslint-plugin-typegpu"],

    env: {
      browser: true,
      builtin: true,
    },

    settings: {
      react: { version: "19.0.0" },
    },

    ignorePatterns: [
      "dist/**",
      "node_modules/**",
      "src/frontend/components/ui/**",
      "src/frontend/ochre/colormap/data/**",
      // .bunli/commands.gen.ts is regenerated by `bunx bunli generate`;
      // it carries embedded JSON literals + raw AST nodes that fmt/lint
      // would churn on every regeneration.
      ".bunli/**",
    ],

    categories: {
      correctness: "error",
      suspicious: "warn",
    },

    rules: {
      // CORRECTNESS
      "no-unused-vars": "off",
      "typescript/no-unused-vars": [
        "warn",
        {
          argsIgnorePattern: "^_",
          varsIgnorePattern: "^_",
          ignoreRestSiblings: true,
        },
      ],

      // REACT HOOKS
      "react/rules-of-hooks": "error",
      "react/exhaustive-deps": "warn",
      "react/only-export-components": ["warn", { allowConstantExport: true }],
      "react/iframe-missing-sandbox": "error",

      // TYPE SAFETY
      "@typescript-eslint/no-explicit-any": "warn",
      "typescript/consistent-type-imports": ["warn", { prefer: "type-imports", fixStyle: "separate-type-imports" }],
      "typescript/no-floating-promises": "error",
      "typescript/no-misused-promises": "error",
      "typescript/return-await": "error",
      "typescript/only-throw-error": "error",
      "typescript/no-deprecated": "error",
      "typescript/no-base-to-string": "error",
      "typescript/no-misused-spread": "error",
      "typescript/no-array-delete": "error",
      "typescript/no-unsafe-enum-comparison": "error",
      "typescript/no-unsafe-function-type": "error",
      "typescript/no-non-null-asserted-nullish-coalescing": "error",
      "typescript/no-non-null-asserted-optional-chain": "error",
      "typescript/no-duplicate-type-constituents": "error",
      "typescript/no-redundant-type-constituents": "error",
      "typescript/no-import-type-side-effects": "error",
      "typescript/no-unnecessary-template-expression": "warn",
      "typescript/prefer-find": "warn",
      "typescript/no-confusing-non-null-assertion": "error",
      "typescript/no-duplicate-enum-values": "error",
      "typescript/no-unnecessary-type-conversion": "warn",
      "typescript/use-unknown-in-catch-callback-variable": "error",

      // TS MODERNIZATION
      "typescript/prefer-nullish-coalescing": "warn",
      "typescript/prefer-optional-chain": "warn",
      "typescript/no-wrapper-object-types": "error",
      "typescript/no-empty-object-type": "warn",
      "typescript/ban-ts-comment": [
        "warn",
        {
          "ts-ignore": "allow-with-description",
          "ts-expect-error": "allow-with-description",
          minimumDescriptionLength: 10,
        },
      ],
      "typescript/prefer-as-const": "warn",
      "typescript/no-unnecessary-type-assertion": "warn",

      // STYLE
      "prefer-const": "error",
      "no-console": "off",
      // Conventional `_`-prefixed private fields (AnnData class, math
      // shorthands like `l_`/`m_`/`s_` in Oklab, exhaustiveness guards
      // `const _exhaustive: never = ...`). Oxlint started enforcing this
      // after the vite-plus 0.1.22 bump; the codebase uses these patterns
      // intentionally.
      "no-underscore-dangle": "off",
      eqeqeq: ["error", "always", { null: "ignore" }],
      "no-var": "error",
      "no-eval": "error",
      "no-unsafe-finally": "error",
      "no-loop-func": "error",
      "no-useless-catch": "error",
      "no-duplicate-case": "error",

      // UNICORN
      "unicorn/prefer-includes": "warn",
      "unicorn/prefer-string-starts-ends-with": "warn",
      "unicorn/prefer-array-flat-map": "warn",
      "unicorn/prefer-negative-index": "warn",
      "unicorn/prefer-array-find": "warn",
      "unicorn/prefer-type-error": "warn",
      "unicorn/no-useless-undefined": "warn",
      "unicorn/no-null": "off",
      "unicorn/no-array-for-each": "off",

      // REACT PERFORMANCE — disabled (too many false positives on stable refs)
      "react-perf/jsx-no-new-array-as-prop": "off",
      "react-perf/jsx-no-new-object-as-prop": "off",
      "react-perf/jsx-no-new-function-as-prop": "off",
      "react-perf/jsx-no-jsx-as-prop": "off",

      // OXC
      "oxc/no-accumulating-spread": "error",
      "oxc/bad-comparison-sequence": "error",
      "oxc/missing-throw": "error",
      "oxc/bad-object-literal-comparison": "error",
      "oxc/bad-char-at-comparison": "error",
      "oxc/bad-min-max-func": "error",
      "oxc/const-comparisons": "error",
      "oxc/double-comparisons": "warn",
      "oxc/erasing-op": "warn",
      "oxc/only-used-in-recursion": "warn",

      // IMPORT HYGIENE
      "import/no-duplicates": "error",
      "import/no-self-import": "error",
      "import/no-cycle": "warn",

      // TYPEGPU (JS plugin) — WGSL-correctness rules for `'use gpu'` functions.
      "typegpu/no-integer-division": "warn",
      "typegpu/no-math": "warn",
      "typegpu/no-uninitialized-variables": "error",
      "typegpu/no-unwrapped-objects": "error",
      "typegpu/no-invalid-assignment": "error",

      // REACT JSX STYLE
      "react/jsx-fragments": ["warn", "syntax"],
      "react/jsx-boolean-value": ["warn", "never"],
      "react/no-unknown-property": "error",
      "react/no-danger": "warn",
      "react/react-in-jsx-scope": "off",
      "react/jsx-no-target-blank": "error",
      "react/jsx-key": ["error", { checkFragmentShorthand: true }],

      // TS BUG CATCHERS
      "typescript/no-for-in-array": "error",
      "typescript/consistent-type-assertions": ["warn", { assertionStyle: "as" }],

      // ASYNC CORRECTNESS
      "require-await": "error",
      "no-promise-executor-return": "error",

      // MODERNIZATION
      "prefer-template": "warn",
      "react/self-closing-comp": ["warn", { html: false }],
      "typescript/array-type": ["warn", { default: "array" }],
      "typescript/unbound-method": "off",
      "typescript/no-unsafe-type-assertion": "off",
      // Overly strict on the React useEffect cleanup-return idiom (return a
      // cleanup on the branch that needs one, otherwise fall through).
      "typescript/consistent-return": "off",
    },

    overrides: [
      {
        // TypeGPU opaque APIs + GPU handle non-null assertions
        files: ["src/frontend/scatter-gpu/**/*.ts", "src/frontend/scatter-gpu/**/*.tsx"],
        rules: {
          "typescript/no-non-null-assertion": "off",
          "@typescript-eslint/no-explicit-any": "off",
          "typescript/no-floating-promises": "warn",
        },
      },
      {
        files: ["**/*.test.ts", "**/*.test.tsx", "**/*.spec.ts", "**/*.spec.tsx"],
        rules: {
          "@typescript-eslint/no-explicit-any": "off",
          "typescript/no-non-null-assertion": "off",
          "typescript/no-floating-promises": "off",
          // `bun:test`'s `expect(...).rejects` returns a thenable that
          // typescript-eslint doesn't recognise — disable the check to keep
          // the common `await expect(fn()).rejects.toThrow()` pattern working.
          "typescript/await-thenable": "off",
        },
      },
      {
        // scripts/* are one-off dev tools using bun:test or top-level await.
        // bun:test's expect(...).rejects.toThrow() is thenable at runtime but
        // typescript-eslint can't see it as a Promise via its types.
        files: ["scripts/**/*.ts"],
        rules: {
          "typescript/await-thenable": "off",
          "require-await": "off",
        },
      },
      {
        // Dedicated Worker globals — `self` is a DedicatedWorkerGlobalScope,
        // so postMessage takes no targetOrigin and async event listeners are fine.
        // Also covers the main-thread call sites that post to dedicated
        // workers (crop-pool.ts, readers.ts) — same reason: no targetOrigin
        // is required for Worker postMessage, only for window postMessage.
        files: [
          "src/zarr/column-worker.ts",
          "src/zarr/parallel-reader.ts",
          "src/zarr/readers.ts",
          "src/server/crop-pool.ts",
          "src/server/crop-worker.ts",
        ],
        rules: {
          "unicorn/require-post-message-target-origin": "off",
          "unicorn/prefer-add-event-listener": "off",
          "typescript/no-misused-promises": "off",
        },
      },
    ],
  },

  // ── Oxfmt ──────────────────────────────────────────────────────────────────
  fmt: {
    printWidth: 120,
    tabWidth: 2,
    useTabs: false,
    semi: true,
    singleQuote: false,
    jsxSingleQuote: false,
    trailingComma: "all",
    arrowParens: "always",
    bracketSpacing: true,
    endOfLine: "lf",
    sortPackageJson: true,
    // - .bunli/commands.gen.ts is regenerated by `bunx bunli generate`
    //   and carries embedded JSON literals + raw AST nodes — fmt would
    //   rewrite shapes the generator overwrites on the next run.
    // - site/ is the zensical build output (gitignored, but oxfmt still
    //   walks the working tree).
    // - zensical.toml is a doc-tool config laid out for human reading;
    //   reflowing it would fight the upstream template's comments.
    // - ochre/colormap/data/** are vendored colormap LUTs hand-packed at
    //   12 numbers per line; oxfmt's `Float32Array.of(...)` rule unpacks
    //   to one number per line, blowing the diff up by 10×.
    ignorePatterns: [".bunli/**", "site/**", "zensical.toml", "src/frontend/ochre/colormap/data/**"],
  },

  // ── Pre-commit (staged files only) ────────────────────────────────────────
  staged: {
    "src/**": "vp check --fix",
  },

  // ── Task runner (vp run) ─────────────────────────────────────────────────
  // `vp run dev <dataset>` (and `bun run dev <dataset>`) both delegate to
  // `scripts/dev.ts`, which captures the positional arg into NDEA_DATASET
  // and dispatches to `dev:all`. Routing the path through env avoids vp's
  // task runner forwarding the positional to every sub-task (which breaks
  // Vite — it interprets a positional path as a project root).
  //
  // Usage:
  //   vp run dev /path/to/data.zarr
  //   bun run dev /path/to/data.zarr
  //   NDEA_DATASET=/path vp run --parallel dev:all  (low-level, skips wrapper)
  run: {
    tasks: {
      dev: {
        // Convenience alias. Forwards positional args to the wrapper, which
        // re-enters `vp run --parallel dev:all` with NDEA_DATASET populated.
        command: "bun scripts/dev.ts",
        cache: false,
      },
      "dev:all": {
        // Composite aggregator — --parallel runs deps simultaneously.
        // cache:false so repeat runs always re-enter the task (a cache hit
        // would replay stdout and mark the task "done", tearing down the
        // still-running children). `true` is a no-op that exits 0.
        dependsOn: ["dev:backend", "dev:frontend"],
        command: "true",
        cache: false,
      },
      "dev:backend": {
        // --hot preserves globalThis (DuckDB, zarr handles) across edits.
        // cache:false because a cache hit would kill the dev server.
        // Env vars (NDEA_DATASET, NDEA_NO_STATIC, NDEA_NO_OPEN) flow through
        // the shell that launches `vp run` — with cache disabled vp does not
        // sandbox the child env.
        command: "bun --hot run src/cli/index.ts",
        cache: false,
      },
      "dev:frontend": {
        command: "vp dev",
        cache: false,
      },

      // Regenerate `.bunli/commands.gen.ts` after any change to
      // `src/cli/commands/**`. The output feeds `@bunli/plugin-completions`
      // (shell completion script generation) and is committed; a CI step
      // (`.github/scripts/check-bunli-gen.sh`) fails if it ever drifts
      // from source. Cache disabled because the generator is fast and
      // we never want a stale cached run.
      gen: {
        command: "bunx bunli generate",
        cache: false,
      },

      // Run the fallow code-health auditor. `vp run` forwards trailing
      // args to the command, so `vp run fallow audit --changed-since
      // main` invokes `bunx fallow audit --changed-since main`. Optional
      // for contributors; not a CI gate. See docs/contributing.md.
      fallow: {
        command: "bunx fallow",
        cache: false,
      },
    },
  },

  // ── Vite bundler (frontend) ───────────────────────────────────────────────
  plugins: [react(), tailwindcss(), typegpuPlugin({}), devErrorReporter(), devConsoleEcho()],
  resolve: {
    alias: { "@": new URL("./src/frontend", import.meta.url).pathname },
  },
  server: {
    // strictPort: false (default) lets Vite walk up from 5173 → 5174 → ...
    // when a worktree sibling is already on 5173. `open: true` opens the
    // actual URL Vite bound (not a hardcoded :5173), solving the "auto-open
    // points at the wrong port" problem we used to patch in scripts/dev.ts.
    open: true,
    proxy: {
      "/data": "http://localhost:5055",
      "/api": "http://localhost:5055",
      "/plate": "http://localhost:5055",
      "/ws": { target: "ws://localhost:5055", ws: true },
      "/mosaic": { target: "ws://localhost:5055", ws: true },
    },
  },
  optimizeDeps: { exclude: ["roaring-wasm"] },
});
