import type { AppShape, PressPlugin } from "fumapress";
import { js2xml } from "xml-js";
import { absoluteUrl } from "./site-url";

const path = "/sitemap.xml";

type UrlElement = {
  loc: { _text: string };
  lastmod?: { _text: string };
  priority?: { _text: string };
};

/**
 * Replaces the upstream sitemap plugin, which resolves each `loc` from a
 * root-relative page URL and therefore drops the Pages project subpath. Its
 * `getEntry` option cannot fix this alone: static routes such as `/blog` and
 * `/blog/tags/*` are resolved internally, and the duplicate check compares
 * against those uncorrected URLs.
 */
export function basePathSitemapPlugin<
  C extends AppShape = AppShape,
>(): PressPlugin<C> {
  return {
    name: "core:sitemap",
    async createPages({ createApiIsomorphic, unstable_getCreated }) {
      createApiIsomorphic({
        render: this.mode === "default" ? "static" : this.mode,
        path,
        handler: async () => {
          const source = await this.getLoader();
          const seen = new Set<string>();
          const urls: UrlElement[] = [];

          for (const page of source.getPages()) {
            const loc = absoluteUrl(page.url, this.siteConfig.baseUrl);
            if (seen.has(loc)) continue;
            seen.add(loc);

            const lastModified = await this.getPageLastModified(page);
            urls.push({
              loc: { _text: loc },
              ...(lastModified
                ? { lastmod: { _text: lastModified.toISOString() } }
                : {}),
              priority: { _text: "0.8" },
            });
          }

          // Routes generated by plugins (blog index, tag pages) are not content
          // pages, so they are only reachable through the router config.
          for (const route of await unstable_getCreated().unstable_getRouterConfigs()) {
            if (!route.isStatic || route.type !== "route") continue;

            const segments = route.path.map((segment) => segment.name);
            if (segments.at(-1) === "404") continue;

            const loc = absoluteUrl(`/${segments.join("/")}`, this.siteConfig.baseUrl);
            if (seen.has(loc)) continue;
            seen.add(loc);

            urls.push({ loc: { _text: loc }, priority: { _text: "1" } });
          }

          const xml = js2xml(
            {
              _declaration: { _attributes: { version: "1.0", encoding: "UTF-8" } },
              urlset: {
                _attributes: { xmlns: "http://www.sitemaps.org/schemas/sitemap/0.9" },
                url: urls,
              },
            },
            { compact: true, spaces: 0 },
          );

          return new Response(xml, {
            headers: { "Content-Type": "application/xml" },
          });
        },
      });
    },
  };
}
