// Generated by scripts/import-cmap-chrisluts.mjs. Do not edit by hand.
// Source: cmap chrisluts (https://github.com/pyapp-kit/cmap/tree/main/src/cmap/data/chrisluts)
// Run `pnpm import:chrisluts` to regenerate.

/** BMR_3C: sequential */
export const BMR_3C_LUT = Float32Array.of(0.0, 0.0, 1.0, 1.0, 0.0, 1.0, 1.0, 0.0, 0.0);

/** BOP_Blue: sequential */
export const BOP_BLUE_LUT = Float32Array.of(0.0, 0.0, 0.0, 0.12549, 0.678431, 0.972549);

/** BOP_Orange: sequential */
export const BOP_ORANGE_LUT = Float32Array.of(0.0, 0.0, 0.0, 0.929412, 0.647059, 0.117647);

/** BOP_Purple: sequential */
export const BOP_PURPLE_LUT = Float32Array.of(0.0, 0.0, 0.0, 0.580392, 0.12549, 0.580392);

/** CGY_3C: sequential */
export const CGY_3C_LUT = Float32Array.of(0.0, 1.0, 1.0, 0.0, 1.0, 0.0, 1.0, 1.0, 0.0);

/** I_Blue: sequential */
export const I_BLUE_LUT = Float32Array.of(1.0, 1.0, 1.0, 0.12549, 0.678431, 0.972549);

/** I_Bordeaux: sequential */
export const I_BORDEAUX_LUT = Float32Array.of(1.0, 1.0, 1.0, 0.8, 0.0, 0.2);

/** I_Cyan: sequential */
export const I_CYAN_LUT = Float32Array.of(1.0, 1.0, 1.0, 0.0, 1.0, 1.0);

/** I_Forest: sequential */
export const I_FOREST_LUT = Float32Array.of(1.0, 1.0, 1.0, 0.0, 0.6, 0.0);

/** I_Green: sequential */
export const I_GREEN_LUT = Float32Array.of(1.0, 1.0, 1.0, 0.0, 1.0, 0.0);

/** I_Magenta: sequential */
export const I_MAGENTA_LUT = Float32Array.of(1.0, 1.0, 1.0, 1.0, 0.0, 1.0);

/** I_Orange: sequential */
export const I_ORANGE_LUT = Float32Array.of(1.0, 1.0, 1.0, 0.929412, 0.647059, 0.117647);

/** I_Purple: sequential */
export const I_PURPLE_LUT = Float32Array.of(1.0, 1.0, 1.0, 0.580392, 0.12549, 0.580392);

/** I_Red: sequential */
export const I_RED_LUT = Float32Array.of(1.0, 1.0, 1.0, 1.0, 0.0, 0.0);

/** I_Yellow: sequential */
export const I_YELLOW_LUT = Float32Array.of(1.0, 1.0, 1.0, 1.0, 1.0, 0.0);

/** OPF_Fresh: sequential */
export const OPF_FRESH_LUT = Float32Array.of(0.0, 0.0, 0.0, 0.0, 1.0, 0.458824);

/** OPF_Orange: sequential */
export const OPF_ORANGE_LUT = Float32Array.of(0.0, 0.0, 0.0, 1.0, 0.458824, 0.0);

/** OPF_Purple: sequential */
export const OPF_PURPLE_LUT = Float32Array.of(0.0, 0.0, 0.0, 0.458824, 0.0, 1.0);

/** RMB_3C: sequential */
export const RMB_3C_LUT = Float32Array.of(1.0, 0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 1.0);

/** YGC_3C: sequential */
export const YGC_3C_LUT = Float32Array.of(1.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 1.0);
