// Generated by scripts/import-cmap-observable.mjs. Do not edit by hand.
// Source: cmap observable (https://github.com/pyapp-kit/cmap/tree/main/src/cmap/data/observable)
// Run `pnpm import:observable` to regenerate.

/** observable10: qualitative */
export const OBSERVABLE10_LUT = Float32Array.of(
  0.258824,
  0.411765,
  0.815686,
  0.937255,
  0.694118,
  0.094118,
  1.0,
  0.447059,
  0.360784,
  0.423529,
  0.772549,
  0.690196,
  0.235294,
  0.662745,
  0.317647,
  1.0,
  0.541176,
  0.717647,
  0.643137,
  0.388235,
  0.94902,
  0.592157,
  0.733333,
  0.960784,
  0.611765,
  0.419608,
  0.305882,
  0.580392,
  0.596078,
  0.627451,
);
