// Generated by scripts/import-cmap-okabeito.mjs. Do not edit by hand.
// Source: cmap okabeito (https://github.com/pyapp-kit/cmap/tree/main/src/cmap/data/okabeito)
// Run `pnpm import:okabeito` to regenerate.

/** okabeito: unknown */
export const OKABEITO_LUT = Float32Array.of(
  0.0,
  0.0,
  0.0,
  0.901961,
  0.623529,
  0.0,
  0.337255,
  0.705882,
  0.913725,
  0.0,
  0.619608,
  0.45098,
  0.941176,
  0.894118,
  0.258824,
  0.0,
  0.447059,
  0.698039,
  0.835294,
  0.368627,
  0.0,
  0.8,
  0.47451,
  0.654902,
);
