// Generated by scripts/import-cmap-vispy.mjs. Do not edit by hand.
// Source: cmap vispy (https://github.com/pyapp-kit/cmap/tree/main/src/cmap/data/vispy)
// Run `pnpm import:vispy` to regenerate.

/** GrBu: diverging */
export const GRBU_LUT = Float32Array.of(0.27873, 0.630178, 0.352795, 0.92, 0.92, 0.92, 0.391967, 0.555535, 0.887736);

/** GrBu_d: diverging */
export const GRBU_D_LUT = Float32Array.of(
  0.27873,
  0.630178,
  0.352795,
  0.133,
  0.133,
  0.133,
  0.391967,
  0.555535,
  0.887736,
);

/** PuGr: diverging */
export const PUGR_LUT = Float32Array.of(0.381375, 0.135274, 0.6102, 0.92, 0.92, 0.92, 0.092783, 0.312003, 0.20554);

/** RdBu: diverging */
export const RDBU_LUT = Float32Array.of(0.753749, 0.332515, 0.226836, 0.92, 0.92, 0.92, 0.247901, 0.493604, 0.569575);

/** RdYeBuCy: diverging */
export const RDYEBUCY_LUT = Float32Array.of(
  0.0,
  1.0,
  1.0,
  0.0,
  0.0,
  1.0,
  0.0,
  0.0,
  1.0,
  1.0,
  0.0,
  0.0,
  1.0,
  0.0,
  0.0,
  1.0,
  1.0,
  0.0,
);

export const RDYEBUCY_POS = Float32Array.of(0.0, 0.17, 0.335, 0.665, 0.88, 1.0);

/** diverging: diverging */
export const DIVERGING_LUT = Float32Array.of(
  0.430059,
  0.672429,
  0.996757,
  0.92,
  0.92,
  0.92,
  0.997537,
  0.531176,
  0.438296,
);

/** hsl: miscellaneous */
export const HSL_LUT = Float32Array.of(
  1.0,
  0.0,
  0.0,
  1.0,
  1.0,
  0.0,
  0.0,
  1.0,
  0.0,
  0.0,
  1.0,
  1.0,
  0.0,
  0.0,
  1.0,
  1.0,
  0.0,
  1.0,
);

/** husl: miscellaneous */
export const HUSL_LUT = Float32Array.of(
  0.997347,
  0.51225,
  0.622706,
  0.826038,
  0.636407,
  0.043821,
  0.363692,
  0.750495,
  0.042938,
  0.050447,
  0.74269,
  0.688584,
  0.144372,
  0.701642,
  0.996769,
  0.922823,
  0.493448,
  0.996696,
);

/** ice: sequential */
export const ICE_LUT = Float32Array.of(0.0, 0.0, 1.0, 1.0, 1.0, 1.0);

/** light_blues: sequential */
export const LIGHT_BLUES_LUT = Float32Array.of(0.9, 0.96666, 1.0, 0.2, 0.733333, 1.0);

/** orange: sequential */
export const ORANGE_LUT = Float32Array.of(1.0, 0.958333, 0.9, 1.0, 0.666667, 0.2);
