#!/usr/bin/env bun

/**
 * sync-version — propagate `package.json.version` into `src/cli/version.ts`.
 *
 * Run as a pre-build hook so the compiled binary embeds the same version
 * the package.json declares. The release workflow calls this before
 * tagging + building.
 *
 * Usage:
 *   bun run scripts/sync-version.ts
 *
 * Exits non-zero with a clear message if the file drift is larger than
 * expected (e.g. package.json missing version, or the target file is not
 * the expected shape).
 */

import { resolve } from "node:path";

const ROOT = resolve(import.meta.dir, "..");
const PKG_PATH = resolve(ROOT, "package.json");
const TARGET_PATH = resolve(ROOT, "src/cli/version.ts");

const pkg: unknown = await Bun.file(PKG_PATH).json();
const version = pkg && typeof pkg === "object" && "version" in pkg ? pkg.version : undefined;

if (typeof version !== "string" || version.length === 0) {
  console.error(`sync-version: package.json is missing a valid "version" field (got ${typeof version})`);
  process.exit(1);
}

// Basic sanity: semver-ish. We don't enforce strict semver because pre-releases
// like `0.2.0-rc1` are legitimate.
if (!/^\d+\.\d+\.\d+(?:[-+].*)?$/.test(version)) {
  console.error(`sync-version: "${version}" does not look like a semver — aborting`);
  process.exit(1);
}

const contents = `// AUTO-GENERATED by scripts/sync-version.ts — do not edit.
// Mirrors the \`version\` field of package.json. Regenerate via
// \`bun run scripts/sync-version.ts\`.
export const VERSION = ${JSON.stringify(version)};
`;

const current = await Bun.file(TARGET_PATH)
  .text()
  .catch(() => "");
if (current === contents) {
  console.log(`sync-version: ${TARGET_PATH.replace(`${ROOT}/`, "")} already at ${version}`);
  process.exit(0);
}

await Bun.write(TARGET_PATH, contents);
console.log(`sync-version: wrote ${version} → ${TARGET_PATH.replace(`${ROOT}/`, "")}`);
