#!/usr/bin/env bun

/**
 * ndea CLI — nd-embedding-atlas viewer + self-updater.
 *
 * Built on @bunli/core: type-safe commands with Zod-validated options, a
 * plugin lifecycle (setup → beforeCommand → handler → afterCommand), and
 * built-in shell-completion / agent-format support. See bunli.dev for
 * the full feature set.
 *
 * Subcommands:
 *   view       Open zarr stores in the dashboard (default)
 *   install    Stage B of the self-installer (called by install.sh)
 *   update     Stage a new release for next launch
 *   rollback   Restore the previous binary
 *
 * For backwards compatibility, invocations without a subcommand default
 * to `view`:
 *     ndea ./data.zarr
 *     ndea project.yaml --port 8080
 *
 * The pending-update auto-applier runs at the root so every command —
 * including `ndea --version` and `ndea --help` — picks up a freshly-
 * staged binary before dispatching.
 */

import { createCLI } from "@bunli/core";
import { completionsPlugin } from "@bunli/plugin-completions";
import rollbackCommand from "./commands/rollback.ts";
import updateCommand from "./commands/update.ts";
import viewCommand from "./commands/view.ts";
import { applyPendingUpdate } from "./lib/pending-update.ts";
import { viewCompletionPlugin } from "./lib/view-completion-plugin.ts";
import { VERSION } from "./version.ts";

const DESCRIPTION =
  "Interactive browser-based dashboard linking AI embeddings to source 5D (TCZYX) image data.\n\n" +
  "Default (no subcommand) runs 'view' — e.g. 'ndea ./data.zarr'.";

/**
 * Names of subcommands that should NOT fall through to `view`. Includes
 * commands injected by plugins — `completions` (script generator) and
 * `complete` (dynamic completion callback) come from
 * `@bunli/plugin-completions`. Without these entries `ndea completions
 * zsh` would be reinterpreted as `ndea view completions zsh`.
 */
const KNOWN_SUBCOMMANDS = new Set(["view", "update", "rollback", "completions", "complete"]);

/**
 * Subcommands that own the install/update lifecycle and must skip the
 * auto-applier. Running it here would race with `update --force` or hide
 * a `rollback` intent.
 */
const SKIP_AUTO_APPLY = new Set(["update", "rollback"]);

/**
 * Normalize rawArgs so `ndea ./data.zarr` routes to `view ./data.zarr`.
 *
 * Bunli dispatches on the first positional token: if it's a known
 * subcommand we leave it alone; otherwise we prepend `view` so the
 * dashboard opens with the original arguments intact. `--help` /
 * `--version` without a subcommand stay at the root so bunli's built-in
 * usage/version output runs.
 *
 * Additional fallback: if no positional is given but NDEA_DATASET is set
 * (the dev-orchestration path via `vp run --parallel dev:all`), route to
 * `view` so the env-var gets picked up inside view.ts.
 */
function normalizeArgs(rawArgs: string[]): string[] {
  const firstPositional = rawArgs.find((a) => !a.startsWith("-"));
  if (firstPositional && !KNOWN_SUBCOMMANDS.has(firstPositional)) {
    return ["view", ...rawArgs];
  }
  if (!firstPositional && typeof process.env.NDEA_DATASET === "string" && process.env.NDEA_DATASET.length > 0) {
    return ["view", ...rawArgs];
  }
  return rawArgs;
}

async function main(): Promise<void> {
  const argv = normalizeArgs(process.argv.slice(2));

  // Apply any staged update BEFORE dispatching to subcommand. If the swap
  // succeeds the function re-execs the new binary and never returns.
  // Skip for install/update/rollback so we don't clobber an in-flight
  // lifecycle command.
  const subcommand = argv.find((a) => !a.startsWith("-")) ?? "view";
  if (!SKIP_AUTO_APPLY.has(subcommand)) {
    const result = await applyPendingUpdate();
    if (result === "applied") return;
  }

  const cli = await createCLI({
    name: "ndea",
    version: VERSION,
    description: DESCRIPTION,
    // Adds `ndea completions <bash|zsh|fish>` (script generator)
    // and `ndea complete -- <args...>` (dynamic completion callback used by
    // the generated shell scripts). Reads command metadata from
    // `.bunli/commands.gen.ts` — regenerated by `bunx bunli generate`
    // whenever the command surface changes.
    // Plugin order matters — bunli runs `beforeCommand` hooks in the order
    // plugins are registered. `viewCompletionPlugin` MUST come before
    // `completionsPlugin` so it can short-circuit the `complete` dispatch
    // when the user is completing a `view` positional path.
    plugins: [
      viewCompletionPlugin,
      completionsPlugin({
        commandName: "ndea",
        executable: "ndea",
      }),
    ],
  });

  cli.command(viewCommand);
  cli.command(updateCommand);
  cli.command(rollbackCommand);

  await cli.run(argv);
}

void main();
