// AUTO-GENERATED by scripts/sync-version.ts — do not edit.
// Mirrors the `version` field of package.json. Regenerate via
// `bun run scripts/sync-version.ts`.
export const VERSION = "0.1.0-beta.2";
