// This file was automatically generated by Bunli.
// You should NOT make any changes in this file as it will be overwritten.

import type { Command, CLI, GeneratedOptionMeta, RegisteredCommands, CommandOptions, GeneratedCommandMeta } from '@bunli/core'
import { createGeneratedHelpers, registerGeneratedStore } from '@bunli/core'

import Doctor from '../apps/ndea/src/cli/commands/doctor.js'
import Gc from '../apps/ndea/src/cli/commands/gc.js'
import Plugin from '../apps/ndea/src/cli/commands/plugin/index.js'
import Rollback from '../apps/ndea/src/cli/commands/rollback.js'
import Update from '../apps/ndea/src/cli/commands/update.js'
import View from '../apps/ndea/src/cli/commands/view.js'

// Narrow list of command names to avoid typeof-cycles in types
const names = ['doctor', 'gc', 'plugin', 'rollback', 'update', 'view'] as const
type GeneratedNames = typeof names[number]

const modules: Record<GeneratedNames, Command<any>> = {
  'doctor': Doctor,
  'gc': Gc,
  'plugin': Plugin,
  'rollback': Rollback,
  'update': Update,
  'view': View
} as const

const metadata: Record<GeneratedNames, GeneratedCommandMeta> = {
  'doctor': {
      name: 'doctor',
      description: 'Diagnose the ndea install (paths, symlink, versions, manifest)',
      options: {
        'check-network': { type: 'z.coerce.boolean.default', required: true, hasDefault: true, default: false, description: 'Also probe manifest.json reachability over the network', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":1280,"end":1285,"loc":{"start":{"line":34,"column":55,"index":1280},"end":{"line":34,"column":60,"index":1285}},"value":false}}]}, validator: '(val) => true' },
        'strict': { type: 'z.coerce.boolean.default', required: true, hasDefault: true, default: false, description: 'Treat soft warnings as errors (non-zero exit)', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":1421,"end":1426,"loc":{"start":{"line":37,"column":46,"index":1421},"end":{"line":37,"column":51,"index":1426}},"value":false}}]}, validator: '(val) => true' }
      },
      path: './apps/ndea/src/cli/commands/doctor'
    },
  'gc': {
      name: 'gc',
      description: 'Prune old installed ndea versions from the versions tree',
      options: {
        'keep': { type: 'z.coerce.number.int.min.default', required: true, hasDefault: true, default: 2, description: 'Number of versions to keep (active counts; default: 2)', min: 1, minLength: 1, schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"NumericLiteral","start":1004,"end":1005,"loc":{"start":{"line":25,"column":56,"index":1004},"end":{"line":25,"column":57,"index":1005}},"extra":{"rawValue":2,"raw":"2"},"value":2}}]}, validator: '(val) => true' },
        'all': { type: 'z.coerce.boolean.default', required: true, hasDefault: true, default: false, description: 'Keep only the active version (overrides --keep)', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":1138,"end":1143,"loc":{"start":{"line":28,"column":43,"index":1138},"end":{"line":28,"column":48,"index":1143}},"value":false}}]}, validator: '(val) => true' }
      },
      path: './apps/ndea/src/cli/commands/gc'
    },
  'plugin': {
      name: 'plugin',
      description: 'Validate and configure trusted custom-node plugins',
      commands: [
        {
          name: 'plugin/validate',
          description: 'Validate a plugin package without executing its client code',
          path: './apps/ndea/src/cli/commands/plugin/validate'
        },
        {
          name: 'plugin/list',
          description: 'List configured user plugin roots in discovery order',
          path: './apps/ndea/src/cli/commands/plugin/list'
        },
        {
          name: 'plugin/enable',
          description: 'Enable a user plugin package for the next session',
          path: './apps/ndea/src/cli/commands/plugin/enable'
        },
        {
          name: 'plugin/disable',
          description: 'Disable a user plugin package for the next session',
          path: './apps/ndea/src/cli/commands/plugin/disable'
        }
      ],
      path: './apps/ndea/src/cli/commands/plugin/index'
    },
  'rollback': {
      name: 'rollback',
      description: 'Switch the active ndea binary to the previous installed version',
      path: './apps/ndea/src/cli/commands/rollback'
    },
  'update': {
      name: 'update',
      description: 'Download the latest ndea release and switch to it',
      options: {
        'force': { type: 'z.coerce.boolean.default', required: true, hasDefault: true, default: false, description: 'Update even when already on the target version', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":1669,"end":1674,"loc":{"start":{"line":46,"column":45,"index":1669},"end":{"line":46,"column":50,"index":1674}},"value":false}}]}, validator: '(val) => true' },
        'channel': { type: 'z.enum.optional', required: false, hasDefault: false, schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'no-gc': { type: 'z.coerce.boolean.default', required: true, hasDefault: true, default: false, schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":1925,"end":1930,"loc":{"start":{"line":52,"column":47,"index":1925},"end":{"line":52,"column":52,"index":1930}},"value":false}}]}, validator: '(val) => true' }
      },
      path: './apps/ndea/src/cli/commands/update'
    },
  'view': {
      name: 'view',
      description: 'Open one or more zarr stores (or a YAML project config) in the dashboard',
      options: {
        'port': { type: 'z.coerce.number.int.min.max.optional', required: false, hasDefault: false, description: 'Server port (default: 5055)', min: 1, max: 65535, minLength: 1, maxLength: 65535, schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'host': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Server host (default: 127.0.0.1)', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'no-open': { type: 'z.coerce.boolean.default', required: true, hasDefault: true, default: false, description: 'Do not auto-open the browser', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":987,"end":992,"loc":{"start":{"line":25,"column":49,"index":987},"end":{"line":25,"column":54,"index":992}},"value":false}}]}, validator: '(val) => true' },
        'no-static': { type: 'z.coerce.boolean.default', required: true, hasDefault: true, default: false, description: 'Do not serve the frontend bundle (dev mode)', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":1107,"end":1112,"loc":{"start":{"line":28,"column":51,"index":1107},"end":{"line":28,"column":56,"index":1112}},"value":false}}]}, validator: '(val) => true' },
        'obs-columns': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Comma-separated obs columns to include', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'preset': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Named preset a shipped build opens (default: annotate)', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' }
      },
      path: './apps/ndea/src/cli/commands/view'
    }
} as const

export const generated = registerGeneratedStore(createGeneratedHelpers(modules, metadata))

export const commands = generated.commands
export const commandMeta = generated.metadata

export interface GeneratedCLI {
  register(cli?: CLI<any>): GeneratedCLI
  list(): Array<{
    name: GeneratedNames
    command: (typeof modules)[GeneratedNames]
    metadata: (typeof metadata)[GeneratedNames]
  }>
  get<Name extends GeneratedNames>(name: Name): (typeof modules)[Name]
  getMetadata<Name extends GeneratedNames>(name: Name): (typeof metadata)[Name]
  getFlags<Name extends keyof RegisteredCommands & string>(name: Name): CommandOptions<Name>
  getFlagsMeta<Name extends GeneratedNames>(name: Name): Record<string, GeneratedOptionMeta>
  withCLI(cli: CLI<any>): { execute(name: string, options: unknown): Promise<void> }
}

export const cli: GeneratedCLI = {
  register: (cliInstance?: CLI<any>) => { generated.register(cliInstance); return cli },
  list: () => generated.list(),
  get: <Name extends GeneratedNames>(name: Name) => generated.get(name),
  getMetadata: <Name extends GeneratedNames>(name: Name) => generated.getMetadata(name),
  getFlags: <Name extends keyof RegisteredCommands & string>(name: Name) => generated.getFlags(name) as CommandOptions<Name>,
  getFlagsMeta: <Name extends GeneratedNames>(name: Name) => generated.getFlagsMeta(name),
  withCLI: (cliInstance) => generated.withCLI(cliInstance)
}

// Enhanced helper functions
export const listCommands = () => generated.list().map(c => c.name)
export const getCommandApi = <Name extends GeneratedNames>(name: Name) => generated.getMetadata(name)
export const getTypedFlags = <Name extends GeneratedNames>(name: Name) => generated.getFlags(name) as CommandOptions<Name>
export const validateCommand = <Name extends GeneratedNames>(name: Name, flags: Record<string, unknown>) => generated.validateCommand(name, flags)
export const findCommandByName = <Name extends GeneratedNames>(name: Name) => generated.findByName(name)
export const findCommandsByDescription = (searchTerm: string) => generated.findByDescription(searchTerm)
export const getCommandNames = () => generated.getCommandNames()

// Auto-register on import for zero-config usage
export default cli

// Ensure module augmentation happens on import
declare module '@bunli/core' {
  // Precise key mapping without typeof cycles
  interface RegisteredCommands extends Record<GeneratedNames, Command<any>> {}
}
