// This file was automatically generated by Bunli.
// You should NOT make any changes in this file as it will be overwritten.

import type { Command, CLI, GeneratedOptionMeta, RegisteredCommands, CommandOptions, GeneratedCommandMeta } from '@bunli/core'
import { createGeneratedHelpers, registerGeneratedStore } from '@bunli/core'

import Doctor from '../apps/ndea/src/cli/commands/doctor.js'
import Gc from '../apps/ndea/src/cli/commands/gc.js'
import Plugin from '../apps/ndea/src/cli/commands/plugin/index.js'
import Update from '../apps/ndea/src/cli/commands/update.js'
import View from '../apps/ndea/src/cli/commands/view.js'

// Narrow list of command names to avoid typeof-cycles in types
const names = ['doctor', 'gc', 'plugin', 'update', 'view'] as const
type GeneratedNames = typeof names[number]

const modules: Record<GeneratedNames, Command<any>> = {
  'doctor': Doctor,
  'gc': Gc,
  'plugin': Plugin,
  'update': Update,
  'view': View
} as const

const metadata: Record<GeneratedNames, GeneratedCommandMeta> = {
  'doctor': {
      name: 'doctor',
      description: 'Diagnose the ndea install (paths, manager, versions, releases)',
      options: {
        'check-network': { type: 'z.coerce.boolean.default', required: true, hasDefault: true, default: false, description: 'Also probe GitHub Releases API reachability over the network', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":1347,"end":1352,"loc":{"start":{"line":34,"column":55,"index":1347},"end":{"line":34,"column":60,"index":1352}},"value":false}}]}, validator: '(val) => true' },
        'strict': { type: 'z.coerce.boolean.default', required: true, hasDefault: true, default: false, description: 'Treat soft warnings as errors (non-zero exit)', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":1522,"end":1527,"loc":{"start":{"line":38,"column":46,"index":1522},"end":{"line":38,"column":51,"index":1527}},"value":false}}]}, validator: '(val) => true' }
      },
      path: './apps/ndea/src/cli/commands/doctor'
    },
  'gc': {
      name: 'gc',
      description: 'Prune old installed ndea versions from the versions tree',
      options: {
        'keep': { type: 'z.coerce.number.int.min.default', required: true, hasDefault: true, default: 1, description: 'Number of versions to keep (active counts; default: 1)', min: 1, minLength: 1, schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"NumericLiteral","start":1001,"end":1002,"loc":{"start":{"line":24,"column":56,"index":1001},"end":{"line":24,"column":57,"index":1002}},"extra":{"rawValue":1,"raw":"1"},"value":1}}]}, validator: '(val) => true' }
      },
      path: './apps/ndea/src/cli/commands/gc'
    },
  'plugin': {
      name: 'plugin',
      description: 'Validate and configure trusted custom-node plugins',
      commands: [
        {
          name: 'plugin/validate',
          description: 'Validate a plugin package without executing its client code',
          path: './apps/ndea/src/cli/commands/plugin/validate'
        },
        {
          name: 'plugin/list',
          description: 'List configured user plugin roots in discovery order',
          path: './apps/ndea/src/cli/commands/plugin/list'
        },
        {
          name: 'plugin/enable',
          description: 'Enable a user plugin package for the next session',
          path: './apps/ndea/src/cli/commands/plugin/enable'
        },
        {
          name: 'plugin/disable',
          description: 'Disable a user plugin package for the next session',
          path: './apps/ndea/src/cli/commands/plugin/disable'
        }
      ],
      path: './apps/ndea/src/cli/commands/plugin/index'
    },
  'update': {
      name: 'update',
      description: 'Download the latest ndea release and switch to it',
      options: {
        'force': { type: 'z.coerce.boolean.default', required: true, hasDefault: true, default: false, description: 'Update even when already on the target version', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":1672,"end":1677,"loc":{"start":{"line":43,"column":45,"index":1672},"end":{"line":43,"column":50,"index":1677}},"value":false}}]}, validator: '(val) => true' },
        'channel': { type: 'z.enum.optional', required: false, hasDefault: false, schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'no-gc': { type: 'z.coerce.boolean.default', required: true, hasDefault: true, default: false, description: 'Skip the post-update gc that removes inactive versions', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":1956,"end":1961,"loc":{"start":{"line":50,"column":47,"index":1956},"end":{"line":50,"column":52,"index":1961}},"value":false}}]}, validator: '(val) => true' }
      },
      path: './apps/ndea/src/cli/commands/update'
    },
  'view': {
      name: 'view',
      description: 'Open one or more Zarr stores (or a YAML project config) in the Node Workspace',
      options: {
        'port': { type: 'z.coerce.number.int.min.max.optional', required: false, hasDefault: false, description: 'Server port (default: 5055)', min: 1, max: 65535, minLength: 1, maxLength: 65535, schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'host': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Server host (default: 127.0.0.1)', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'no-open': { type: 'z.coerce.boolean.default', required: true, hasDefault: true, default: false, description: 'Do not auto-open the browser', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":996,"end":1001,"loc":{"start":{"line":25,"column":49,"index":996},"end":{"line":25,"column":54,"index":1001}},"value":false}}]}, validator: '(val) => true' },
        'no-static': { type: 'z.coerce.boolean.default', required: true, hasDefault: true, default: false, description: 'Do not serve the frontend bundle (dev mode)', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":1144,"end":1149,"loc":{"start":{"line":29,"column":51,"index":1144},"end":{"line":29,"column":56,"index":1149}},"value":false}}]}, validator: '(val) => true' },
        'obs-columns': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Comma-separated obs columns to include', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'preset': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Named preset a shipped build opens (default: annotate)', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' }
      },
      path: './apps/ndea/src/cli/commands/view'
    }
} as const

export const generated = registerGeneratedStore(createGeneratedHelpers(modules, metadata))

export const commands = generated.commands
export const commandMeta = generated.metadata

export interface GeneratedCLI {
  register(cli?: CLI<any>): GeneratedCLI
  list(): Array<{
    name: GeneratedNames
    command: (typeof modules)[GeneratedNames]
    metadata: (typeof metadata)[GeneratedNames]
  }>
  get<Name extends GeneratedNames>(name: Name): (typeof modules)[Name]
  getMetadata<Name extends GeneratedNames>(name: Name): (typeof metadata)[Name]
  getFlags<Name extends keyof RegisteredCommands & string>(name: Name): CommandOptions<Name>
  getFlagsMeta<Name extends GeneratedNames>(name: Name): Record<string, GeneratedOptionMeta>
  withCLI(cli: CLI<any>): { execute(name: string, options: unknown): Promise<void> }
}

export const cli: GeneratedCLI = {
  register: (cliInstance?: CLI<any>) => { generated.register(cliInstance); return cli },
  list: () => generated.list(),
  get: <Name extends GeneratedNames>(name: Name) => generated.get(name),
  getMetadata: <Name extends GeneratedNames>(name: Name) => generated.getMetadata(name),
  getFlags: <Name extends keyof RegisteredCommands & string>(name: Name) => generated.getFlags(name) as CommandOptions<Name>,
  getFlagsMeta: <Name extends GeneratedNames>(name: Name) => generated.getFlagsMeta(name),
  withCLI: (cliInstance) => generated.withCLI(cliInstance)
}

// Enhanced helper functions
export const listCommands = () => generated.list().map(c => c.name)
export const getCommandApi = <Name extends GeneratedNames>(name: Name) => generated.getMetadata(name)
export const getTypedFlags = <Name extends GeneratedNames>(name: Name) => generated.getFlags(name) as CommandOptions<Name>
export const validateCommand = <Name extends GeneratedNames>(name: Name, flags: Record<string, unknown>) => generated.validateCommand(name, flags)
export const findCommandByName = <Name extends GeneratedNames>(name: Name) => generated.findByName(name)
export const findCommandsByDescription = (searchTerm: string) => generated.findByDescription(searchTerm)
export const getCommandNames = () => generated.getCommandNames()

// Auto-register on import for zero-config usage
export default cli

// Ensure module augmentation happens on import
declare module '@bunli/core' {
  // Precise key mapping without typeof cycles
  interface RegisteredCommands extends Record<GeneratedNames, Command<any>> {}
}
