#!/usr/bin/env bun

/**
 * ndea CLI: nd-embedding-atlas viewer + self-updater.
 *
 * Built on @bunli/core: type-safe commands with Zod-validated options, a
 * plugin lifecycle (setup → beforeCommand → handler → afterCommand), and
 * built-in shell-completion / agent-format support. See bunli.dev for
 * the full feature set.
 *
 * Subcommands:
 *   view       Open Zarr stores in the Node Workspace (default)
 *   update     Download a new release and switch the active symlink
 *   rollback   Switch to the previous installed version
 *   gc         Prune old installed versions
 *   doctor     Diagnose the install (paths, symlink, versions)
 *   plugin     Validate and configure trusted custom-node plugins
 *
 * For backwards compatibility, invocations without a subcommand default
 * to `view`:
 *     ndea ./data.zarr
 *     ndea project.yaml --port 8080
 */

// Side-effect import: extracts embedded libduckdb (when bundled at build
// time) and dlopen's it with RTLD_GLOBAL BEFORE any duckdb-touching module
// loads. ES module post-order evaluation guarantees this runs ahead of
// `viewCommand` → `startup.ts` → `server/store.ts` (the first place
// @duckdb/node-api is evaluated). No-op in dev mode.
// eslint-disable-next-line import/no-unassigned-import
import "./lib/preload-libduckdb.ts";

import { createCLI } from "@bunli/core";
import { completionsPlugin } from "@bunli/plugin-completions";
import doctorCommand from "./commands/doctor.ts";
import gcCommand from "./commands/gc.ts";
import pluginCommand from "./commands/plugin/index.ts";
import rollbackCommand from "./commands/rollback.ts";
import updateCommand from "./commands/update.ts";
import viewCommand from "./commands/view.ts";
import { viewCompletionPlugin } from "./lib/view-completion-plugin.ts";
import { generatedCommandsPath } from "./lib/generated-commands-path.ts";
import { VERSION } from "./version.ts";

const DESCRIPTION =
  "Interactive browser-based Node Workspace linking AI embeddings to source 5D (TCZYX) image data.\n\n" +
  "Default (no subcommand) runs 'view': e.g. 'ndea ./data.zarr'.";

/**
 * Names of subcommands that should NOT fall through to `view`. Includes
 * commands injected by plugins: `completions` (script generator) and
 * `complete` (dynamic completion callback) come from
 * `@bunli/plugin-completions`. Without these entries `ndea completions
 * zsh` would be reinterpreted as `ndea view completions zsh`.
 */
const KNOWN_SUBCOMMANDS = new Set(["view", "update", "rollback", "gc", "doctor", "plugin", "completions", "complete"]);

/**
 * Normalize rawArgs so `ndea ./data.zarr` routes to `view ./data.zarr`.
 *
 * Bunli dispatches on the first positional token: if it's a known
 * subcommand we leave it alone; otherwise we prepend `view` so the
 * Workspace opens with the original arguments intact. `--help` /
 * `--version` without a subcommand stay at the root so bunli's built-in
 * usage/version output runs.
 *
 * Additional fallback: if no positional is given but NDEA_DATASET is set
 * (the dev-orchestration path via `vp run --parallel dev:all`), route to
 * `view` so the env-var gets picked up inside view.ts.
 */
function normalizeArgs(rawArgs: string[]): string[] {
  const firstPositional = rawArgs.find((a) => !a.startsWith("-"));
  if (firstPositional && !KNOWN_SUBCOMMANDS.has(firstPositional)) {
    return ["view", ...rawArgs];
  }
  if (!firstPositional && typeof process.env.NDEA_DATASET === "string" && process.env.NDEA_DATASET.length > 0) {
    return ["view", ...rawArgs];
  }
  return rawArgs;
}

async function main(): Promise<void> {
  const argv = normalizeArgs(process.argv.slice(2));

  const cli = await createCLI({
    name: "ndea",
    version: VERSION,
    description: DESCRIPTION,
    // Adds `ndea completions <bash|zsh|fish>` (script generator)
    // and `ndea complete -- <args...>` (dynamic completion callback used by
    // the generated shell scripts). Reads command metadata from
    // `.bunli/commands.gen.ts`: regenerated by `bunx bunli generate`
    // whenever the command surface changes.
    // Plugin order matters: bunli runs `beforeCommand` hooks in the order
    // plugins are registered. `viewCompletionPlugin` MUST come before
    // `completionsPlugin` so it can short-circuit the `complete` dispatch
    // when the user is completing a `view` positional path.
    plugins: [
      viewCompletionPlugin,
      completionsPlugin({
        commandName: "ndea",
        executable: "ndea",
        generatedPath: generatedCommandsPath(),
      }),
    ],
  });

  cli.command(viewCommand);
  cli.command(updateCommand);
  cli.command(rollbackCommand);
  cli.command(gcCommand);
  cli.command(doctorCommand);
  cli.command(pluginCommand);

  await cli.run(argv);
}

void main();
