// AUTO-GENERATED by scripts/build.ts when --bundle-duckdb is set.
// Dev-mode stub: null path. build.ts overwrites with a real
// `with { type: "file" }` import before compile, then restores.
//
// When non-null, the path points into $bunfs/ inside the compiled
// binary. `preload-libduckdb.ts` reads the bytes and dlopens an
// extracted copy so duckdb.node's @rpath/libduckdb.<ext> dependency
// is satisfied without a sidecar file on disk.

export const LIBDUCKDB_EMBEDDED_PATH: string | null = null;
