/**
 * Shared content for the `ndea` POSIX-sh wrapper script written into every
 * `~/.ndea/versions/<tag>/` directory.
 *
 * The wrapper exists so the bun-compiled binary (`ndea.bin`) can find its
 * sibling `libduckdb.so` at runtime on Linux. Bun extracts `duckdb.node`
 * (which `DT_NEEDED libduckdb.so`) to a randomized /tmp path; without
 * `LD_LIBRARY_PATH` pointing at the install dir, dlopen fails.
 *
 * macOS doesn't strictly need the wrapper — `@executable_path/libduckdb.dylib`
 * is patched into duckdb.node at build time. But shipping the same layout
 * everywhere keeps install / update / rollback code uniform, and dyld
 * ignores LD_LIBRARY_PATH so the export is harmless on macOS.
 *
 * The binary writes this content to disk on demand via a hidden
 * `__write-wrapper` subcommand; install.sh and update.ts both invoke that,
 * so this TS const is the single source of truth.
 */
export const WRAPPER_SCRIPT_CONTENT = `#!/bin/sh
# Auto-generated by ndea install / update — sets LD_LIBRARY_PATH so the
# sibling libduckdb shared library is findable when the embedded
# duckdb.node is dlopen'd. macOS doesn't need this (rpath patched at
# build time); LD_LIBRARY_PATH is ignored by dyld there. Single layout.
#
# NDEA_LAUNCHER carries the path the user actually invoked (potentially
# the PATH-resolved symlink at $NDEA_BIN_DIR/ndea). \`ndea update\` /
# \`ndea rollback\` need that to know which symlink to atomically swap;
# without it they only see \`ndea.bin\` after exec.
target=$(realpath "$0")
dir=$(dirname "$target")
export LD_LIBRARY_PATH="\${dir}\${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"
export NDEA_LAUNCHER="$0"
exec "\${dir}/ndea.bin" "$@"
`;
