#!/usr/bin/env bun

/**
 * Build the nd-embedding-atlas single binary.
 *
 * Steps:
 *   1. Build frontend (vp build)
 *   2. Enumerate dist/frontend/** files for embedding
 *   3. Compile binary (bun build --compile) with embedded frontend assets
 *
 * The `--compile` flag is only available via the Bun CLI, not the JS API,
 * so this script shells out to `bun build`.
 *
 * Usage:
 *   bun run scripts/build.ts                          # current platform
 *   bun run scripts/build.ts bun-linux-x64            # specific target
 *   bun run scripts/build.ts --skip-frontend           # skip frontend build
 */

import { existsSync } from "node:fs";
import { resolve } from "node:path";

// ─── Args ──────────────────────────────────────────────────────────────────

const args = Bun.argv.slice(2);
const skipFrontend = args.includes("--skip-frontend");
const targetArg = args.find((a) => !a.startsWith("--"));
const target = targetArg ?? `bun-${process.platform}-${process.arch}`;

const ROOT = resolve(import.meta.dir, "..");
const FRONTEND_DIST = resolve(ROOT, "dist/frontend");
const OUT_DIR = resolve(ROOT, "dist");

// ─── ANSI helpers ──────────────────────────────────────────────────────────

const BOLD = "\x1b[1m";
const DIM = "\x1b[2m";
const GREEN = "\x1b[32m";
const RED = "\x1b[31m";
const RESET = "\x1b[0m";

// ─── Step 1: Build frontend ────────────────────────────────────────────────

if (!skipFrontend) {
  console.log(`\n  ${BOLD}Step 1:${RESET} Building frontend...\n`);
  const frontendProc = Bun.spawn(["vp", "build"], {
    cwd: ROOT,
    stdout: "inherit",
    stderr: "inherit",
  });
  const exitCode = await frontendProc.exited;
  if (exitCode !== 0) {
    console.error(`\n  ${RED}Frontend build failed with exit code ${exitCode}${RESET}`);
    process.exit(1);
  }
  console.log(`  ${GREEN}✓${RESET} Frontend built`);
} else {
  console.log(`\n  ${DIM}Skipping frontend build (--skip-frontend)${RESET}`);
}

// Verify dist/frontend exists
if (!existsSync(FRONTEND_DIST)) {
  console.error(`\n  ${RED}Error:${RESET} dist/frontend/ not found. Run without --skip-frontend.`);
  process.exit(1);
}

// ─── Step 2: Enumerate frontend assets + generate import manifest ──────────
//
// We can't pass the JS bundle as an entrypoint to `bun build --compile`
// (it would try to parse it — top-level await in the minified output fails).
// Instead, generate a TS module with `import ... with { type: "file" }`
// declarations. Bun embeds those files into $bunfs at compile time, and the
// import returns a path string that works in both dev and compiled mode.

console.log(`\n  ${BOLD}Step 2:${RESET} Generating embedded-assets manifest...`);

const glob = new Bun.Glob("**/*");
const assetPaths: string[] = [];
for await (const path of glob.scan({ cwd: FRONTEND_DIST, onlyFiles: true })) {
  assetPaths.push(path);
}

const manifestLines: string[] = [
  "// AUTO-GENERATED by scripts/build.ts — do not edit.",
  "// Maps frontend asset relative paths to their resolved file paths.",
  "// In dev mode paths point at dist/frontend/; in compiled binaries they",
  '// resolve to $bunfs/ entries embedded via `with { type: "file" }`.',
  "",
];
for (let i = 0; i < assetPaths.length; i++) {
  const p = assetPaths[i];
  manifestLines.push(`import _${i} from "../../dist/frontend/${p}" with { type: "file" };`);
}
manifestLines.push("");
manifestLines.push("export const EMBEDDED_ASSETS: Record<string, string> = {");
for (let i = 0; i < assetPaths.length; i++) {
  manifestLines.push(`    ${JSON.stringify(assetPaths[i])}: _${i},`);
}
manifestLines.push("};");
manifestLines.push("");

const manifestPath = resolve(ROOT, "src/server/__generated-embedded-assets.ts");
await Bun.write(manifestPath, manifestLines.join("\n"));

console.log(`  ${GREEN}✓${RESET} ${assetPaths.length} assets manifested → ${manifestPath.replace(`${ROOT}/`, "")}`);

// ─── Step 3: Compile binary ────────────────────────────────────────────────

console.log(`\n  ${BOLD}Step 3:${RESET} Compiling binary for ${target}...\n`);

const outfile = resolve(OUT_DIR, "ndea");

// @duckdb/node-bindings/duckdb.js branches through every platform's
// native addon via require(). Only the matching optional dep is installed;
// the others must be externalized so the bundler doesn't try to resolve them.
const DUCKDB_PLATFORM_EXTERNALS = [
  "@duckdb/node-bindings-linux-x64/duckdb.node",
  "@duckdb/node-bindings-linux-arm64/duckdb.node",
  "@duckdb/node-bindings-darwin-x64/duckdb.node",
  "@duckdb/node-bindings-darwin-arm64/duckdb.node",
  "@duckdb/node-bindings-win32-x64/duckdb.node",
  "@duckdb/node-bindings-win32-arm64/duckdb.node",
];

// Worker scripts must be passed as additional entrypoints so the bundler
// recursively resolves their imports. Bun emits each as `<name>.js` next
// to the main entry inside $bunfs; parallel-reader.ts switches its URL
// extension to match when running compiled.
const WORKER_ENTRYPOINTS = ["./src/zarr/column-worker.ts"];

const compileArgs = [
  "bun",
  "build",
  "./src/cli/index.ts",
  ...WORKER_ENTRYPOINTS,
  "--compile",
  `--target=${target}`,
  `--outfile=${outfile}`,
  "--bytecode",
  "--minify",
  ...DUCKDB_PLATFORM_EXTERNALS.flatMap((m) => ["--external", m]),
];

const compileProc = Bun.spawn(compileArgs, {
  cwd: ROOT,
  stdout: "inherit",
  stderr: "inherit",
});

const compileExit = await compileProc.exited;

// Always restore the manifest stub so the working tree stays clean.
const restoreProc = Bun.spawn(["git", "restore", "src/server/__generated-embedded-assets.ts"], {
  cwd: ROOT,
  stdout: "ignore",
  stderr: "ignore",
});
await restoreProc.exited;

if (compileExit !== 0) {
  console.error(`\n  ${RED}Compile failed with exit code ${compileExit}${RESET}`);
  process.exit(1);
}

// ─── Done ──────────────────────────────────────────────────────────────────

const stat = Bun.file(outfile);
const sizeMB = (stat.size / 1024 / 1024).toFixed(1);

console.log(`\n  ${GREEN}✓${RESET} Binary: ${BOLD}${outfile}${RESET} (${sizeMB} MB)`);
console.log(`  ${DIM}Target: ${target}${RESET}\n`);
