#!/usr/bin/env bun

/**
 * sync-version — stamp the runtime version into `src/cli/version.ts`.
 *
 * Version source, in priority order:
 *   1. an explicit argument / `NDEA_VERSION` env — the release workflow passes
 *      `github.event.release.tag_name` here. The git tag is the source of
 *      truth; a leading "v" is tolerated.
 *   2. `package.json.version` — the local-dev default.
 *
 * The semver check below doubles as the release guard: a mistyped tag fails
 * the build here rather than shipping a bad `--version`.
 *
 * Usage:
 *   bun run scripts/sync-version.ts                 # local: from package.json
 *   bun run scripts/sync-version.ts v0.1.0-beta.3   # CI: from the release tag
 */

import { resolve } from "node:path";

const ROOT = resolve(import.meta.dir, "..");
const PKG_PATH = resolve(ROOT, "package.json");
const TARGET_PATH = resolve(ROOT, "src/cli/version.ts");

interface Pkg {
  version?: unknown;
}

const pkg = (await Bun.file(PKG_PATH).json()) as Pkg;

// Explicit version (release tag) wins over package.json. Strip a leading "v"
// so a raw git tag like `v0.1.0-beta.3` works as-is.
const override = (Bun.argv[2] ?? process.env.NDEA_VERSION ?? "").trim().replace(/^v/, "");
const version: unknown = override.length > 0 ? override : pkg.version;

if (typeof version !== "string" || version.length === 0) {
  console.error(`sync-version: no valid version (arg/NDEA_VERSION/package.json all empty; got ${typeof version})`);
  process.exit(1);
}

// Basic sanity: semver-ish. We don't enforce strict semver because pre-releases
// like `0.2.0-rc1` are legitimate.
if (!/^\d+\.\d+\.\d+(?:[-+].*)?$/.test(version)) {
  console.error(`sync-version: "${version}" does not look like a semver — aborting`);
  process.exit(1);
}

const contents = `// AUTO-GENERATED by scripts/sync-version.ts — do not edit.
// Stamped from the release tag in CI, else package.json locally. Regenerate
// via \`bun run scripts/sync-version.ts\`.
export const VERSION = ${JSON.stringify(version)};
`;

const current = await Bun.file(TARGET_PATH)
  .text()
  .catch(() => "");
if (current === contents) {
  console.log(`sync-version: ${TARGET_PATH.replace(`${ROOT}/`, "")} already at ${version}`);
  process.exit(0);
}

await Bun.write(TARGET_PATH, contents);
console.log(`sync-version: wrote ${version} → ${TARGET_PATH.replace(`${ROOT}/`, "")}`);
