// Generated by scripts/import-cmap-contrib.mjs. Do not edit by hand.

import { linearFromLut } from "../build";
import * as data from "../data/contrib.generated";

export const araucaria = linearFromLut({ name: "araucaria", lut: data.ARAUCARIA_LUT });
export const cerrado = linearFromLut({ name: "cerrado", lut: data.CERRADO_LUT });
export const pampa = linearFromLut({ name: "pampa", lut: data.PAMPA_LUT });
export const pantanal = linearFromLut({ name: "pantanal", lut: data.PANTANAL_LUT });
