// Generated by scripts/import-cmap-tableau.mjs. Do not edit by hand.

import { discreteFromRgbLut } from "../build";
import * as data from "../data/tableau.generated";

export const tab10 = discreteFromRgbLut("tab10", data.TAB10_LUT);
export const tab10_colorblind = discreteFromRgbLut("tab10_colorblind", data.TAB10_COLORBLIND_LUT);
export const tab10_light = discreteFromRgbLut("tab10_light", data.TAB10_LIGHT_LUT);
export const tab10_medium = discreteFromRgbLut("tab10_medium", data.TAB10_MEDIUM_LUT);
export const tab10_new = discreteFromRgbLut("tab10_new", data.TAB10_NEW_LUT);
export const tab20 = discreteFromRgbLut("tab20", data.TAB20_LUT);
export const tab20b = discreteFromRgbLut("tab20b", data.TAB20B_LUT);
export const tab20c = discreteFromRgbLut("tab20c", data.TAB20C_LUT);
export const tab_traffic_light = discreteFromRgbLut("tab_traffic_light", data.TAB_TRAFFIC_LIGHT_LUT);
