/**
 * Cross-language parity: every curve, distance and aggregation must match shrimPy's
 * `DesirabilityModel` to floating-point precision.
 *
 * This is the test that matters most in the node. The profile tuned in this UI is exported as
 * YAML and consumed by the acquisition, so a curve that scores differently here than in Python
 * means the microscope images fields the operator did not choose — silently, with no error.
 *
 * `data/parity.json` is generated by `data/parity.py`, which imports the actual
 * `fov_model.py` and runs it. Regenerate after any change to the Python:
 *
 *     gh api 'repos/czbiohub-sf/shrimPy/contents/shrimpy/fov_selection/fov_model.py?ref=smart-fov-selection' \
 *       -H 'Accept: application/vnd.github.raw' > /tmp/fov_model.py
 *     uv run --script data/parity.py > data/parity.json
 *
 * The fixture is gitignored (it lives under `data/`), so the suite skips rather than fails
 * when it is absent — a missing fixture is an environment gap, not a regression. CI should
 * generate it; see SRI-55.
 */

import { describe, expect, test } from "bun:test";
import {
  aggregate,
  curveBounds,
  curveParams,
  desirability,
  MISSING_DESIRABILITY,
  MISSING_Z2,
  squaredDistance,
  type Aggregation,
  type CurveBounds,
  type Direction,
  type Shape,
} from "./desirability";

interface ParityCase {
  shape: Shape;
  direction: Direction;
  params: Record<string, number>;
  bounds: CurveBounds;
  roundTrip: Record<string, number>;
  /** null = NaN input, i.e. the missing-value contract. */
  d: (number | null)[];
  z2: (number | null)[];
}

interface Parity {
  xs: (number | null)[];
  cases: ParityCase[];
  aggregate: {
    d: number[];
    z2: number[];
    w: number[];
    results: Record<Aggregation, number>;
  };
}

const FIXTURE = new URL("../../../../data/parity.json", import.meta.url).pathname;

async function loadParity(): Promise<Parity | null> {
  const file = Bun.file(FIXTURE);
  return (await file.exists()) ? ((await file.json()) as Parity) : null;
}

const parity = await loadParity();

// Python emits float64; the arithmetic is identical, so agreement should be near-exact.
// 1e-12 catches a wrong constant or a transposed formula while tolerating last-bit drift.
const PRECISION = 1e-12;

describe("desirability parity with shrimPy fov_model.py", () => {
  test("the generated fixture is present", () => {
    if (!parity) {
      console.warn(`[parity] ${FIXTURE} absent — run 'uv run --script data/parity.py > data/parity.json'`);
    }
    // Not an assertion on the fixture: the suite must stay green without it.
    expect(true).toBe(true);
  });

  if (!parity) return;

  const xs = parity.xs.map((x) => x ?? Number.NaN);

  for (const c of parity.cases) {
    const label = `${c.shape}/${c.direction} ${JSON.stringify(c.params)}`;

    test(`${label} — interpretable params convert to the same internal bounds`, () => {
      const bounds = curveBounds(c.shape, c.direction, c.params);
      expect(bounds.lo).toBeCloseTo(c.bounds.lo, 12);
      expect(bounds.hi).toBeCloseTo(c.bounds.hi, 12);
      expect(bounds.softLeft).toBeCloseTo(c.bounds.softLeft, 12);
      expect(bounds.softRight).toBeCloseTo(c.bounds.softRight, 12);
      expect(bounds.curveK).toBeCloseTo(c.bounds.curveK, 12);
    });

    test(`${label} — bounds convert back to the same interpretable params`, () => {
      const round = curveParams(c.shape, c.direction, c.bounds);
      for (const [key, expected] of Object.entries(c.roundTrip)) {
        expect(round[key]).toBeCloseTo(expected, 10);
      }
    });

    test(`${label} — desirability matches at every sample`, () => {
      const bounds = curveBounds(c.shape, c.direction, c.params);
      xs.forEach((x, i) => {
        const actual = desirability(x, c.shape, c.direction, bounds);
        const expected = c.d[i];
        if (expected == null) throw new Error("python emitted null for a non-NaN d");
        expect(Math.abs(actual - expected)).toBeLessThan(PRECISION);
      });
    });

    test(`${label} — squared distance matches at every sample`, () => {
      const bounds = curveBounds(c.shape, c.direction, c.params);
      xs.forEach((x, i) => {
        const actual = squaredDistance(x, c.shape, c.direction, bounds);
        const expected = c.z2[i];
        if (expected == null) throw new Error("python emitted null for a non-NaN z2");
        // z2 is unbounded above; compare relatively once the magnitude is large.
        const tolerance = Math.max(PRECISION, Math.abs(expected) * 1e-12);
        expect(Math.abs(actual - expected)).toBeLessThan(tolerance);
      });
    });
  }

  test("a missing value yields zero desirability and the explicit distance penalty", () => {
    // Not derived from the fixture: this is the contract that stops a NaN from reading as
    // ideal for a "lower is better" feature.
    const bounds = curveBounds("gaussian", "target", { center: 0.5, fwhm: 0.2 });
    expect(desirability(Number.NaN, "gaussian", "target", bounds)).toBe(MISSING_DESIRABILITY);
    expect(squaredDistance(Number.NaN, "gaussian", "target", bounds)).toBe(MISSING_Z2);
  });

  test("all three aggregations match", () => {
    const { d, z2, w, results } = parity.aggregate;
    for (const [mode, expected] of Object.entries(results) as [Aggregation, number][]) {
      expect(Math.abs(aggregate(mode, d, z2, w) - expected)).toBeLessThan(PRECISION);
    }
  });

  test("gaussian aggregation vetoes hardest, sum compensates most", () => {
    // Reading of the numbers rather than a restatement: with one missing feature the joint
    // gaussian collapses ~1700x below the compensatory mean.
    const { d, z2, w, results } = parity.aggregate;
    expect(results.gaussian).toBeLessThan(results.product);
    expect(results.product).toBeLessThan(results.sum);
    expect(aggregate("sum", d, z2, w)).toBeGreaterThan(0.4);
    expect(aggregate("gaussian", d, z2, w)).toBeLessThan(0.001);
  });
});
