/**
 * Port of shrimPy's `DesirabilityModel` (`shrimpy/fov_selection/fov_model.py`).
 *
 * This must agree with the Python numerically, not just in spirit: the config tuned here is
 * handed to the acquisition, and a curve that scores differently offline than online would
 * silently image the wrong fields. `desirability.parity.test.ts` pins every branch against
 * values generated by running the Python itself.
 *
 * Two representations, and the distinction matters:
 *
 * - **Interpretable params** are what configs and editors use — "where it's best" plus "how
 *   forgiving": `center`/`fwhm`, `center`/`fold`, `midpoint`/`width`, `onset`/`ideal`.
 * - **Internal bounds** `(lo, hi, softLeft, softRight, curveK)` are what the curves consume.
 *
 * `curveBounds` and `curveParams` are exact inverses, so a GUI can edit the same knobs the
 * config carries without drifting from it.
 */

/** FWHM = 2·sqrt(2·ln2)·sigma, so sigma = fwhm · this. */
const FWHM_TO_SIGMA = 1 / (2 * Math.sqrt(2 * Math.LN2));
/** Half-width at half maximum, in log space, for the lognormal's fold tolerance. */
const HWHM_TO_SIGMA = 1 / Math.sqrt(2 * Math.LN2);
/** A logistic's 10%→90% rise spans `width`. */
const SIGMOID_10_90 = Math.log(81);

/**
 * A missing feature contributes ZERO desirability, for every direction — a NaN means the
 * feature could not be measured (too few objects segmented), which is evidence of a
 * degenerate field, not of an ideal value. Critically it is NOT imputed to a raw 0, which
 * for a "lower is better" feature would read as perfect.
 */
export const MISSING_DESIRABILITY = 0;

/**
 * Squared distance charged to an unmeasurable feature under the gaussian aggregation: 10
 * sigma. Deliberately finite and explicit rather than infinite, so a feature measured
 * FURTHER off-target than this counts as worse than one that could not be measured at all —
 * a 15-sigma coverage is positive evidence of a bad field, a NaN is only absent evidence.
 */
export const MISSING_Z2 = 100;

/** Floor before any log, so one zero drives the score low without producing -Infinity. */
const DESIRABILITY_FLOOR = 1e-6;

export const SHAPES = ["linear", "sigmoid", "gaussian", "lognormal"] as const;
export type Shape = (typeof SHAPES)[number];

export const DIRECTIONS = ["target", "higher", "lower"] as const;
export type Direction = (typeof DIRECTIONS)[number];

export const AGGREGATIONS = ["sum", "product", "gaussian"] as const;
export type Aggregation = (typeof AGGREGATIONS)[number];

/** A FOV is only good if EVERY feature is acceptable, so the default vetoes rather than averages. */
export const DEFAULT_AGGREGATION: Aggregation = "gaussian";

/** Internal curve parameters, as the desirability functions consume them. */
export interface CurveBounds {
  lo: number;
  hi: number;
  /** Linear-target shoulder widths; unused by every other shape. */
  softLeft: number;
  softRight: number;
  /** Gaussian/lognormal tail exponent, or the logistic's sharpness. 0 means "shape default". */
  curveK: number;
}

/** Interpretable parameters, keyed as the YAML config keys them. */
export type CurveParams = Record<string, number>;

const clamp01 = (v: number) => (v < 0 ? 0 : v > 1 ? 1 : v);
/** Python's `(hi - lo) or 1e-9`: an exactly-zero span becomes a tiny one. */
const spanOf = (lo: number, hi: number) => (hi - lo === 0 ? 1e-9 : hi - lo);

// ─── interpretable ⇄ internal ────────────────────────────────────────────────

/** `center` peak + `fwhm` width at half maximum → the ±1σ points. */
export function gaussianBounds(center: number, fwhm: number): { lo: number; hi: number } {
  if (!(fwhm > 0)) throw new Error(`gaussian 'fwhm' must be > 0; got ${fwhm}`);
  const sigma = fwhm * FWHM_TO_SIGMA;
  return { lo: center - sigma, hi: center + sigma };
}

/** `center` peak + `fold` multiplicative tolerance (d = 0.5 at center·fold and center/fold). */
export function lognormalBounds(center: number, fold: number): { lo: number; hi: number } {
  if (!(center > 0)) throw new Error(`lognormal 'center' must be > 0; got ${center}`);
  if (!(fold > 1)) throw new Error(`lognormal 'fold' must be > 1; got ${fold}`);
  const s = Math.log(fold) * HWHM_TO_SIGMA;
  return { lo: center * Math.exp(-s), hi: center * Math.exp(s) };
}

/** Interpretable params → internal bounds. Inverse of {@link curveParams}. */
export function curveBounds(shape: Shape, direction: Direction, params: CurveParams): CurveBounds {
  if (shape === "gaussian") {
    const { lo, hi } = gaussianBounds(params.center, params.fwhm);
    return { lo, hi, softLeft: 0, softRight: 0, curveK: 0 };
  }
  if (shape === "lognormal") {
    const { lo, hi } = lognormalBounds(params.center, params.fold);
    return { lo, hi, softLeft: 0, softRight: 0, curveK: 0 };
  }
  if (shape === "sigmoid") {
    if (direction === "target") {
      const lo = params.half_band_lo;
      const hi = params.half_band_hi;
      return {
        lo,
        hi,
        softLeft: 0,
        softRight: 0,
        curveK: (SIGMOID_10_90 * (hi - lo)) / (params.width || 1e-9),
      };
    }
    const mid = params.midpoint;
    const w = params.width;
    return { lo: mid - 0.5 * w, hi: mid + 0.5 * w, softLeft: 0, softRight: 0, curveK: SIGMOID_10_90 };
  }
  if (direction === "target") {
    return {
      lo: params.range_lo,
      hi: params.range_hi,
      softLeft: params.soft_left,
      softRight: params.soft_right,
      curveK: 0,
    };
  }
  const { onset, ideal } = params;
  return direction === "higher"
    ? { lo: onset, hi: ideal, softLeft: 0, softRight: 0, curveK: 0 }
    : { lo: ideal, hi: onset, softLeft: 0, softRight: 0, curveK: 0 };
}

/** Internal bounds → interpretable params. Inverse of {@link curveBounds}. */
export function curveParams(shape: Shape, direction: Direction, b: CurveBounds): CurveParams {
  if (shape === "gaussian") {
    return { center: 0.5 * (b.lo + b.hi), fwhm: (0.5 * (b.hi - b.lo)) / FWHM_TO_SIGMA };
  }
  if (shape === "lognormal") {
    const s = 0.5 * Math.log(Math.max(b.hi, 1e-12) / Math.max(b.lo, 1e-12));
    return {
      center: Math.sqrt(Math.max(b.lo, 1e-12) * Math.max(b.hi, 1e-12)),
      fold: Math.exp(s / HWHM_TO_SIGMA),
    };
  }
  if (shape === "sigmoid") {
    const width = (SIGMOID_10_90 * (b.hi - b.lo)) / (b.curveK || 6);
    return direction === "target"
      ? { half_band_lo: b.lo, half_band_hi: b.hi, width }
      : { midpoint: 0.5 * (b.lo + b.hi), width };
  }
  if (direction === "target") {
    return { range_lo: b.lo, range_hi: b.hi, soft_left: b.softLeft, soft_right: b.softRight };
  }
  return direction === "higher" ? { onset: b.lo, ideal: b.hi } : { onset: b.hi, ideal: b.lo };
}

// ─── the curves ──────────────────────────────────────────────────────────────

/**
 * Desirability of one value in [0, 1].
 *
 * `linear` is the only BOUNDED shape — it reaches exactly 0 and 1. The others are
 * asymptotic: their tails approach 0 without arriving, which is why {@link squaredDistance}
 * cannot recover a usable distance by inverting them.
 */
export function desirability(value: number, shape: Shape, direction: Direction, b: CurveBounds): number {
  if (!Number.isFinite(value)) return MISSING_DESIRABILITY;
  const { lo, hi, softLeft, softRight, curveK } = b;
  const span = spanOf(lo, hi);

  if (shape === "gaussian") {
    const c = 0.5 * (lo + hi);
    const s = Math.max(0.5 * span, 1e-9);
    const beta = curveK > 0 ? curveK : 2;
    return clamp01(Math.exp(-0.5 * Math.abs((value - c) / s) ** beta));
  }

  if (shape === "lognormal") {
    if (value <= 0) return 0; // outside the support
    const loP = Math.max(lo, 1e-12);
    let hiP = Math.max(hi, 1e-12);
    if (hiP <= loP) hiP = loP * (1 + 1e-6);
    const mu = 0.5 * (Math.log(loP) + Math.log(hiP));
    const s = Math.max(0.5 * Math.log(hiP / loP), 1e-9);
    const beta = curveK > 0 ? curveK : 2;
    return clamp01(Math.exp(-0.5 * Math.abs((Math.log(value) - mu) / s) ** beta));
  }

  if (shape === "sigmoid") {
    const k = curveK || 6;
    if (direction === "target") {
      const up = 1 / (1 + Math.exp((-k * (value - lo)) / span));
      const down = 1 / (1 + Math.exp((k * (value - hi)) / span));
      return clamp01(up * down);
    }
    const s = 1 / (1 + Math.exp((-k * (value - 0.5 * (lo + hi))) / span));
    return clamp01(direction === "higher" ? s : 1 - s);
  }

  // linear
  if (direction === "higher") return clamp01((value - lo) / span);
  if (direction === "lower") return clamp01(1 - (value - lo) / span);
  const rising = clamp01(1 - (lo - value) / (softLeft || 1e-9));
  const falling = clamp01(1 - (value - hi) / (softRight || 1e-9));
  return clamp01(Math.min(rising, falling));
}

/**
 * Squared normalised distance from ideal — one axis of the joint gaussian score.
 *
 * Computed from the curve's own parameters, NOT by inverting the desirability. Inverting
 * (`z² = -2 ln d`) saturates the moment `d` hits its floor, capping every distance at
 * ~5.26σ and making all badly-off-target fields score identically; going direct keeps the
 * ranking discriminating arbitrarily far out. `linear` and `sigmoid` have no scale
 * parameter to go direct with, so those do invert, capped at {@link MISSING_Z2}.
 */
export function squaredDistance(value: number, shape: Shape, direction: Direction, b: CurveBounds): number {
  if (!Number.isFinite(value)) return MISSING_Z2;
  const { lo, hi, curveK } = b;
  const span = spanOf(lo, hi);
  const beta = curveK > 0 ? curveK : 2;

  if (shape === "gaussian") {
    const c = 0.5 * (lo + hi);
    const s = Math.max(0.5 * span, 1e-9);
    return Math.abs((value - c) / s) ** beta;
  }
  if (shape === "lognormal") {
    if (value <= 0) return MISSING_Z2;
    const loP = Math.max(lo, 1e-12);
    let hiP = Math.max(hi, 1e-12);
    if (hiP <= loP) hiP = loP * (1 + 1e-6);
    const mu = 0.5 * (Math.log(loP) + Math.log(hiP));
    const s = Math.max(0.5 * Math.log(hiP / loP), 1e-9);
    return Math.abs((Math.log(value) - mu) / s) ** beta;
  }
  const d = desirability(value, shape, direction, b);
  return Math.min(-2 * Math.log(clamp01(d)), MISSING_Z2);
}

// ─── aggregation ─────────────────────────────────────────────────────────────

/**
 * One score per FOV from the per-feature desirabilities `d` and distances `z2`.
 *
 * `sum`      weighted arithmetic mean — COMPENSATORY: a strong feature offsets a weak one,
 *            so good coverage can mask a starved centre.
 * `product`  weighted geometric mean — any feature near zero drags the whole score down, so
 *            gate features act as vetoes.
 * `gaussian` NOT a combination of the per-feature scores at all: one N-dimensional gaussian
 *            over the raw distances, `exp(-0.5 · Σw·z² / Σw)`, with diagonal covariance whose
 *            axes are the features' sigmas. Falls fastest as more features fall short.
 *            Dividing by Σw makes it a geometric mean of the per-axis gaussians, which is a
 *            monotonic rescale — ranking is untouched, but scores stay comparable when the
 *            feature count changes and cannot underflow to a tie.
 *
 * Missing features keep their weight in the denominator under `sum`, so they pull the score
 * down proportionally rather than being quietly ignored.
 */
export function aggregate(
  aggregation: Aggregation,
  d: readonly number[],
  z2: readonly number[],
  w: readonly number[],
): number {
  const total = w.reduce((a, b) => a + b, 0) || 1;
  if (aggregation === "sum") {
    return d.reduce((acc, di, i) => acc + w[i] * di, 0) / total;
  }
  if (aggregation === "product") {
    const logs = d.reduce((acc, di, i) => acc + w[i] * Math.log(Math.min(Math.max(di, DESIRABILITY_FLOOR), 1)), 0);
    return Math.exp(logs / total);
  }
  const sum = z2.reduce((acc, zi, i) => acc + w[i] * zi, 0);
  return Math.exp((-0.5 * sum) / total);
}

// ─── the profile ─────────────────────────────────────────────────────────────

/** One feature's contribution to the score, as the YAML config expresses it. */
export interface FeatureSpec {
  shape: Shape;
  direction: Direction;
  params: CurveParams;
  weight: number;
  /** Excluded features keep their tuning but contribute nothing. */
  enabled: boolean;
}

export interface ScoreProfile {
  aggregation: Aggregation;
  /** Feature name → spec. Only enabled entries score. */
  features: Readonly<Record<string, FeatureSpec>>;
}

/**
 * Score one FOV. `values` maps feature name → measured value; a name absent from the row, or
 * holding a non-finite value, counts as missing (see {@link MISSING_DESIRABILITY}).
 *
 * Returns 0 with no enabled features: nothing has been asked for, so nothing ranks.
 */
export function scoreFov(profile: ScoreProfile, values: Readonly<Record<string, number>>): number {
  const names = Object.keys(profile.features).filter((name) => profile.features[name].enabled);
  if (names.length === 0) return 0;

  const d: number[] = [];
  const z2: number[] = [];
  const w: number[] = [];
  for (const name of names) {
    const spec = profile.features[name];
    const bounds = curveBounds(spec.shape, spec.direction, spec.params);
    const value = values[name];
    d.push(desirability(value, spec.shape, spec.direction, bounds));
    z2.push(squaredDistance(value, spec.shape, spec.direction, bounds));
    w.push(spec.weight);
  }
  return aggregate(profile.aggregation, d, z2, w);
}
